/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { appendBracket } from '../runtime';
import {
    type API,
    APIFromJSON,
    APIToJSON,
} from '../models/API';

export interface ApiHandlerRequest {
    aPI: API;
}

export interface MediaGateRequest {
    file: string;
}

/**
 * ApiApi - interface
 * 
 * @export
 * @interface ApiApiInterface
 */
export interface ApiApiInterface {
    /**
     * Creates request options for apiHandler without sending the request
     * @param {API} aPI 
     * @throws {RequiredError}
     * @memberof ApiApiInterface
     */
    apiHandlerRequestOpts(requestParameters: ApiHandlerRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {API} aPI 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiApiInterface
     */
    apiHandlerRaw(requestParameters: ApiHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<API>>;

    /**
     */
    apiHandler(requestParameters: ApiHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<API>;

    /**
     * Creates request options for mediaGate without sending the request
     * @param {string} file media filename in _upload
     * @throws {RequiredError}
     * @memberof ApiApiInterface
     */
    mediaGateRequestOpts(requestParameters: MediaGateRequest): Promise<runtime.RequestOpts>;

    /**
     * `#[utoipa::path]` here is doc-only — the fn runs as `from_fn` middleware, not a route handler, but the attribute still emits the spec entry so the generated clients get a typed `downloadMedia(file)`. `servers(...)` pins it to femi.market (the global server is api.earnfemi.com); `Request`/`Next` args aren\'t documentable extractors so utoipa ignores them and uses the explicit `params`.
     * @summary Auth + per-GB debit gate in front of the `_upload` ServeDir on femi.market.   - not a media file → pass through (static site, app data, 404), free   - media file that isn\'t a real file in `_upload` → pass through, free   - media file in `_upload` → require Bearer, charge `size × pricing.gb`,     record a debit in the astc ledger, then let ServeDir stream the bytes. The gate only authorizes/charges; ServeDir still does the actual file streaming (range requests, mime, etc.).
     * @param {string} file media filename in _upload
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiApiInterface
     */
    mediaGateRaw(requestParameters: MediaGateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>>;

    /**
     * `#[utoipa::path]` here is doc-only — the fn runs as `from_fn` middleware, not a route handler, but the attribute still emits the spec entry so the generated clients get a typed `downloadMedia(file)`. `servers(...)` pins it to femi.market (the global server is api.earnfemi.com); `Request`/`Next` args aren\'t documentable extractors so utoipa ignores them and uses the explicit `params`.
     * Auth + per-GB debit gate in front of the `_upload` ServeDir on femi.market.   - not a media file → pass through (static site, app data, 404), free   - media file that isn\'t a real file in `_upload` → pass through, free   - media file in `_upload` → require Bearer, charge `size × pricing.gb`,     record a debit in the astc ledger, then let ServeDir stream the bytes. The gate only authorizes/charges; ServeDir still does the actual file streaming (range requests, mime, etc.).
     */
    mediaGate(requestParameters: MediaGateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>>;

}

/**
 * 
 */
export class ApiApi extends runtime.BaseAPI implements ApiApiInterface {

    /**
     * Creates request options for apiHandler without sending the request
     */
    async apiHandlerRequestOpts(requestParameters: ApiHandlerRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['aPI'] == null) {
            throw new runtime.RequiredError(
                'aPI',
                'Required parameter "aPI" was null or undefined when calling apiHandler().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: APIToJSON(requestParameters['aPI']),
        };
    }

    /**
     */
    async apiHandlerRaw(requestParameters: ApiHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<API>> {
        const requestOptions = await this.apiHandlerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => APIFromJSON(jsonValue));
    }

    /**
     */
    async apiHandler(requestParameters: ApiHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<API> {
        const response = await this.apiHandlerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for mediaGate without sending the request
     */
    async mediaGateRequestOpts(requestParameters: MediaGateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling mediaGate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{file}`;
        urlPath = urlPath.replace('{file}', encodeURIComponent(String(requestParameters['file'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * `#[utoipa::path]` here is doc-only — the fn runs as `from_fn` middleware, not a route handler, but the attribute still emits the spec entry so the generated clients get a typed `downloadMedia(file)`. `servers(...)` pins it to femi.market (the global server is api.earnfemi.com); `Request`/`Next` args aren\'t documentable extractors so utoipa ignores them and uses the explicit `params`.
     * Auth + per-GB debit gate in front of the `_upload` ServeDir on femi.market.   - not a media file → pass through (static site, app data, 404), free   - media file that isn\'t a real file in `_upload` → pass through, free   - media file in `_upload` → require Bearer, charge `size × pricing.gb`,     record a debit in the astc ledger, then let ServeDir stream the bytes. The gate only authorizes/charges; ServeDir still does the actual file streaming (range requests, mime, etc.).
     */
    async mediaGateRaw(requestParameters: MediaGateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const requestOptions = await this.mediaGateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * `#[utoipa::path]` here is doc-only — the fn runs as `from_fn` middleware, not a route handler, but the attribute still emits the spec entry so the generated clients get a typed `downloadMedia(file)`. `servers(...)` pins it to femi.market (the global server is api.earnfemi.com); `Request`/`Next` args aren\'t documentable extractors so utoipa ignores them and uses the explicit `params`.
     * Auth + per-GB debit gate in front of the `_upload` ServeDir on femi.market.   - not a media file → pass through (static site, app data, 404), free   - media file that isn\'t a real file in `_upload` → pass through, free   - media file in `_upload` → require Bearer, charge `size × pricing.gb`,     record a debit in the astc ledger, then let ServeDir stream the bytes. The gate only authorizes/charges; ServeDir still does the actual file streaming (range requests, mime, etc.).
     */
    async mediaGate(requestParameters: MediaGateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.mediaGateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
