/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { appendBracket } from '../runtime';
import {
    type API,
    APIFromJSON,
    APIToJSON,
} from '../models/API';

export interface ApiHandlerRequest {
    aPI: API;
}

/**
 * ApiHandlerApi - interface
 * 
 * @export
 * @interface ApiHandlerApiInterface
 */
export interface ApiHandlerApiInterface {
    /**
     * Creates request options for apiHandler without sending the request
     * @param {API} aPI 
     * @throws {RequiredError}
     * @memberof ApiHandlerApiInterface
     */
    apiHandlerRequestOpts(requestParameters: ApiHandlerRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {API} aPI 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiHandlerApiInterface
     */
    apiHandlerRaw(requestParameters: ApiHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<API>>;

    /**
     */
    apiHandler(requestParameters: ApiHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<API>;

}

/**
 * 
 */
export class ApiHandlerApi extends runtime.BaseAPI implements ApiHandlerApiInterface {

    /**
     * Creates request options for apiHandler without sending the request
     */
    async apiHandlerRequestOpts(requestParameters: ApiHandlerRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['aPI'] == null) {
            throw new runtime.RequiredError(
                'aPI',
                'Required parameter "aPI" was null or undefined when calling apiHandler().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: APIToJSON(requestParameters['aPI']),
        };
    }

    /**
     */
    async apiHandlerRaw(requestParameters: ApiHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<API>> {
        const requestOptions = await this.apiHandlerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => APIFromJSON(jsonValue));
    }

    /**
     */
    async apiHandler(requestParameters: ApiHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<API> {
        const response = await this.apiHandlerRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
