/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { appendBracket } from '../runtime';
import {
    type ApiKey,
    ApiKeyFromJSON,
    ApiKeyToJSON,
} from '../models/ApiKey';

export interface ApiKeyRequest {
    id: string;
    userId: string;
    key?: string;
}

/**
 * ApiKeyRouteApi - interface
 * 
 * @export
 * @interface ApiKeyRouteApiInterface
 */
export interface ApiKeyRouteApiInterface {
    /**
     * Creates request options for apiKey without sending the request
     * @param {string} id 
     * @param {string} userId 
     * @param {string} [key] 
     * @throws {RequiredError}
     * @memberof ApiKeyRouteApiInterface
     */
    apiKeyRequestOpts(requestParameters: ApiKeyRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} id 
     * @param {string} userId 
     * @param {string} [key] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiKeyRouteApiInterface
     */
    apiKeyRaw(requestParameters: ApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiKey>>;

    /**
     */
    apiKey(requestParameters: ApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiKey>;

}

/**
 * 
 */
export class ApiKeyRouteApi extends runtime.BaseAPI implements ApiKeyRouteApiInterface {

    /**
     * Creates request options for apiKey without sending the request
     */
    async apiKeyRequestOpts(requestParameters: ApiKeyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiKey().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling apiKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        // use FormData when the endpoint consumes multipart/form-data, URLSearchParams otherwise
        const useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['id'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'id', requestParameters['id']);
        }

        if (requestParameters['key'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'key', requestParameters['key']);
        }

        if (requestParameters['userId'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'user_id', requestParameters['userId']);
        }


        let urlPath = `/api_key`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     */
    async apiKeyRaw(requestParameters: ApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiKey>> {
        const requestOptions = await this.apiKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiKeyFromJSON(jsonValue));
    }

    /**
     */
    async apiKey(requestParameters: ApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiKey> {
        const response = await this.apiKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
