/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { appendBracket } from '../runtime';
import {
    type ApplePay,
    ApplePayFromJSON,
    ApplePayToJSON,
} from '../models/ApplePay';
import {
    type ApplePayStatus,
    ApplePayStatusFromJSON,
    ApplePayStatusToJSON,
} from '../models/ApplePayStatus';

export interface ApplePayRequest {
    credit: number;
    currency: string;
    id: string;
    jws: string;
    loaded: boolean;
    price: number;
    productId: string;
    status: ApplePayStatus;
    transactionId: string;
    userId: string;
}

/**
 * ApplePayRouteApi - interface
 * 
 * @export
 * @interface ApplePayRouteApiInterface
 */
export interface ApplePayRouteApiInterface {
    /**
     * Creates request options for applePay without sending the request
     * @param {number} credit 
     * @param {string} currency 
     * @param {string} id uuid v7
     * @param {string} jws 
     * @param {boolean} loaded 
     * @param {number} price 
     * @param {string} productId 
     * @param {ApplePayStatus} status 
     * @param {string} transactionId 
     * @param {string} userId 
     * @throws {RequiredError}
     * @memberof ApplePayRouteApiInterface
     */
    applePayRequestOpts(requestParameters: ApplePayRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} credit 
     * @param {string} currency 
     * @param {string} id uuid v7
     * @param {string} jws 
     * @param {boolean} loaded 
     * @param {number} price 
     * @param {string} productId 
     * @param {ApplePayStatus} status 
     * @param {string} transactionId 
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApplePayRouteApiInterface
     */
    applePayRaw(requestParameters: ApplePayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApplePay>>;

    /**
     */
    applePay(requestParameters: ApplePayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApplePay>;

}

/**
 * 
 */
export class ApplePayRouteApi extends runtime.BaseAPI implements ApplePayRouteApiInterface {

    /**
     * Creates request options for applePay without sending the request
     */
    async applePayRequestOpts(requestParameters: ApplePayRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['credit'] == null) {
            throw new runtime.RequiredError(
                'credit',
                'Required parameter "credit" was null or undefined when calling applePay().'
            );
        }

        if (requestParameters['currency'] == null) {
            throw new runtime.RequiredError(
                'currency',
                'Required parameter "currency" was null or undefined when calling applePay().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling applePay().'
            );
        }

        if (requestParameters['jws'] == null) {
            throw new runtime.RequiredError(
                'jws',
                'Required parameter "jws" was null or undefined when calling applePay().'
            );
        }

        if (requestParameters['loaded'] == null) {
            throw new runtime.RequiredError(
                'loaded',
                'Required parameter "loaded" was null or undefined when calling applePay().'
            );
        }

        if (requestParameters['price'] == null) {
            throw new runtime.RequiredError(
                'price',
                'Required parameter "price" was null or undefined when calling applePay().'
            );
        }

        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling applePay().'
            );
        }

        if (requestParameters['status'] == null) {
            throw new runtime.RequiredError(
                'status',
                'Required parameter "status" was null or undefined when calling applePay().'
            );
        }

        if (requestParameters['transactionId'] == null) {
            throw new runtime.RequiredError(
                'transactionId',
                'Required parameter "transactionId" was null or undefined when calling applePay().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling applePay().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        // use FormData when the endpoint consumes multipart/form-data, URLSearchParams otherwise
        const useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['credit'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'credit', requestParameters['credit']);
        }

        if (requestParameters['currency'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'currency', requestParameters['currency']);
        }

        if (requestParameters['id'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'id', requestParameters['id']);
        }

        if (requestParameters['jws'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'jws', requestParameters['jws']);
        }

        if (requestParameters['loaded'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'loaded', requestParameters['loaded']);
        }

        if (requestParameters['price'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'price', requestParameters['price']);
        }

        if (requestParameters['productId'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'product_id', requestParameters['productId']);
        }

        if (requestParameters['status'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'status', ApplePayStatusToJSON(requestParameters['status']));
        }

        if (requestParameters['transactionId'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'transaction_id', requestParameters['transactionId']);
        }

        if (requestParameters['userId'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'user_id', requestParameters['userId']);
        }


        let urlPath = `/apple_pay`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     */
    async applePayRaw(requestParameters: ApplePayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApplePay>> {
        const requestOptions = await this.applePayRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApplePayFromJSON(jsonValue));
    }

    /**
     */
    async applePay(requestParameters: ApplePayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApplePay> {
        const response = await this.applePayRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
