/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { appendBracket } from '../runtime';
import {
    type CharacterAlignment,
    CharacterAlignmentFromJSON,
    CharacterAlignmentToJSON,
} from '../models/CharacterAlignment';
import {
    type LyricSync,
    LyricSyncFromJSON,
    LyricSyncToJSON,
} from '../models/LyricSync';
import {
    type WordAlignment,
    WordAlignmentFromJSON,
    WordAlignmentToJSON,
} from '../models/WordAlignment';

export interface LyricSyncRequest {
    audio: string;
    id: string;
    lyrics: string;
    characters?: Array<CharacterAlignment>;
    credit?: number;
    loss?: number;
    userId?: string;
    words?: Array<WordAlignment>;
}

/**
 * LyricSyncRouteApi - interface
 * 
 * @export
 * @interface LyricSyncRouteApiInterface
 */
export interface LyricSyncRouteApiInterface {
    /**
     * Creates request options for lyricSync without sending the request
     * @param {string} audio 
     * @param {string} id 
     * @param {string} lyrics 
     * @param {Array<CharacterAlignment>} [characters] 
     * @param {number} [credit] 
     * @param {number} [loss] 
     * @param {string} [userId] 
     * @param {Array<WordAlignment>} [words] 
     * @throws {RequiredError}
     * @memberof LyricSyncRouteApiInterface
     */
    lyricSyncRequestOpts(requestParameters: LyricSyncRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} audio 
     * @param {string} id 
     * @param {string} lyrics 
     * @param {Array<CharacterAlignment>} [characters] 
     * @param {number} [credit] 
     * @param {number} [loss] 
     * @param {string} [userId] 
     * @param {Array<WordAlignment>} [words] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LyricSyncRouteApiInterface
     */
    lyricSyncRaw(requestParameters: LyricSyncRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LyricSync>>;

    /**
     */
    lyricSync(requestParameters: LyricSyncRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LyricSync>;

}

/**
 * 
 */
export class LyricSyncRouteApi extends runtime.BaseAPI implements LyricSyncRouteApiInterface {

    /**
     * Creates request options for lyricSync without sending the request
     */
    async lyricSyncRequestOpts(requestParameters: LyricSyncRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['audio'] == null) {
            throw new runtime.RequiredError(
                'audio',
                'Required parameter "audio" was null or undefined when calling lyricSync().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling lyricSync().'
            );
        }

        if (requestParameters['lyrics'] == null) {
            throw new runtime.RequiredError(
                'lyrics',
                'Required parameter "lyrics" was null or undefined when calling lyricSync().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        // use FormData when the endpoint consumes multipart/form-data, URLSearchParams otherwise
        const useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['audio'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'audio', requestParameters['audio']);
        }

        if (requestParameters['characters'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'characters', requestParameters['characters']!.map(CharacterAlignmentToJSON));
        }

        if (requestParameters['credit'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'credit', requestParameters['credit']);
        }

        if (requestParameters['id'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'id', requestParameters['id']);
        }

        if (requestParameters['loss'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'loss', requestParameters['loss']);
        }

        if (requestParameters['lyrics'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'lyrics', requestParameters['lyrics']);
        }

        if (requestParameters['userId'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'user_id', requestParameters['userId']);
        }

        if (requestParameters['words'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'words', requestParameters['words']!.map(WordAlignmentToJSON));
        }


        let urlPath = `/lyric_sync`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     */
    async lyricSyncRaw(requestParameters: LyricSyncRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LyricSync>> {
        const requestOptions = await this.lyricSyncRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LyricSyncFromJSON(jsonValue));
    }

    /**
     */
    async lyricSync(requestParameters: LyricSyncRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LyricSync> {
        const response = await this.lyricSyncRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
