/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { appendBracket } from '../runtime';
import {
    type Pay,
    PayFromJSON,
    PayToJSON,
} from '../models/Pay';
import {
    type PayProvider,
    PayProviderFromJSON,
    PayProviderToJSON,
} from '../models/PayProvider';
import {
    type PayStatus,
    PayStatusFromJSON,
    PayStatusToJSON,
} from '../models/PayStatus';

export interface PayRequest {
    id: string;
    provider: PayProvider;
    userId: string;
    credit?: number;
    currency?: string;
    jws?: string;
    loaded?: boolean;
    orderId?: string | null;
    packageName?: string;
    price?: number;
    productId?: string;
    refId?: string;
    status?: PayStatus;
}

/**
 * PayRouteApi - interface
 * 
 * @export
 * @interface PayRouteApiInterface
 */
export interface PayRouteApiInterface {
    /**
     * Creates request options for pay without sending the request
     * @param {string} id uuid v7
     * @param {PayProvider} provider Selects the verification path: Apple App Store vs Google Play.
     * @param {string} userId 
     * @param {number} [credit] 
     * @param {string} [currency] 
     * @param {string} [jws] Signed transaction JWS from StoreKit; the input to Apple verification.
     * @param {boolean} [loaded] 
     * @param {string} [orderId] Google\\\&#39;s per-purchase &#x60;orderId&#x60;, returned by the Play Developer API (not the client). Not used for dedup — &#x60;ref_id&#x60; is — because promo-code purchases may have no &#x60;orderId&#x60;.
     * @param {string} [packageName] 
     * @param {number} [price] 
     * @param {string} [productId] 
     * @param {string} [refId] Globally-unique purchase id, used as the idempotency key for both stores. Apple: the &#x60;transactionId&#x60;, extracted server-side from the verified JWS   (empty on the incoming request — the server fills it in). Google: the &#x60;purchaseToken&#x60;, sent by the client. It is both the input to   Play Developer API verification and the idempotency key.
     * @param {PayStatus} [status] 
     * @throws {RequiredError}
     * @memberof PayRouteApiInterface
     */
    payRequestOpts(requestParameters: PayRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} id uuid v7
     * @param {PayProvider} provider Selects the verification path: Apple App Store vs Google Play.
     * @param {string} userId 
     * @param {number} [credit] 
     * @param {string} [currency] 
     * @param {string} [jws] Signed transaction JWS from StoreKit; the input to Apple verification.
     * @param {boolean} [loaded] 
     * @param {string} [orderId] Google\\\&#39;s per-purchase &#x60;orderId&#x60;, returned by the Play Developer API (not the client). Not used for dedup — &#x60;ref_id&#x60; is — because promo-code purchases may have no &#x60;orderId&#x60;.
     * @param {string} [packageName] 
     * @param {number} [price] 
     * @param {string} [productId] 
     * @param {string} [refId] Globally-unique purchase id, used as the idempotency key for both stores. Apple: the &#x60;transactionId&#x60;, extracted server-side from the verified JWS   (empty on the incoming request — the server fills it in). Google: the &#x60;purchaseToken&#x60;, sent by the client. It is both the input to   Play Developer API verification and the idempotency key.
     * @param {PayStatus} [status] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PayRouteApiInterface
     */
    payRaw(requestParameters: PayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Pay>>;

    /**
     */
    pay(requestParameters: PayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Pay>;

}

/**
 * 
 */
export class PayRouteApi extends runtime.BaseAPI implements PayRouteApiInterface {

    /**
     * Creates request options for pay without sending the request
     */
    async payRequestOpts(requestParameters: PayRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling pay().'
            );
        }

        if (requestParameters['provider'] == null) {
            throw new runtime.RequiredError(
                'provider',
                'Required parameter "provider" was null or undefined when calling pay().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling pay().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        // use FormData when the endpoint consumes multipart/form-data, URLSearchParams otherwise
        const useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['credit'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'credit', requestParameters['credit']);
        }

        if (requestParameters['currency'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'currency', requestParameters['currency']);
        }

        if (requestParameters['id'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'id', requestParameters['id']);
        }

        if (requestParameters['jws'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'jws', requestParameters['jws']);
        }

        if (requestParameters['loaded'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'loaded', requestParameters['loaded']);
        }

        if (requestParameters['orderId'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'order_id', requestParameters['orderId']);
        }

        if (requestParameters['packageName'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'package_name', requestParameters['packageName']);
        }

        if (requestParameters['price'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'price', requestParameters['price']);
        }

        if (requestParameters['productId'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'product_id', requestParameters['productId']);
        }

        if (requestParameters['provider'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'provider', PayProviderToJSON(requestParameters['provider']));
        }

        if (requestParameters['refId'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'ref_id', requestParameters['refId']);
        }

        if (requestParameters['status'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'status', PayStatusToJSON(requestParameters['status']));
        }

        if (requestParameters['userId'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'user_id', requestParameters['userId']);
        }


        let urlPath = `/pay`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     */
    async payRaw(requestParameters: PayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Pay>> {
        const requestOptions = await this.payRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PayFromJSON(jsonValue));
    }

    /**
     */
    async pay(requestParameters: PayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Pay> {
        const response = await this.payRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
