/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { appendBracket } from '../runtime';
import {
    type AudioLine,
    AudioLineFromJSON,
    AudioLineToJSON,
} from '../models/AudioLine';
import {
    type Faq,
    FaqFromJSON,
    FaqToJSON,
} from '../models/Faq';
import {
    type Project,
    ProjectFromJSON,
    ProjectToJSON,
} from '../models/Project';
import {
    type Season,
    SeasonFromJSON,
    SeasonToJSON,
} from '../models/Season';

export interface ProjectRequest {
    about: string;
    audio: string;
    audioLines: Array<AudioLine>;
    faqs: Array<Faq>;
    genre: string;
    id: string;
    playlist: string;
    seasons: Array<Season>;
    summary: string;
    userId: string;
}

/**
 * ProjectRouteApi - interface
 * 
 * @export
 * @interface ProjectRouteApiInterface
 */
export interface ProjectRouteApiInterface {
    /**
     * Creates request options for project without sending the request
     * @param {string} about 
     * @param {string} audio 
     * @param {Array<AudioLine>} audioLines 
     * @param {Array<Faq>} faqs 
     * @param {string} genre 
     * @param {string} id 
     * @param {string} playlist 
     * @param {Array<Season>} seasons 
     * @param {string} summary 
     * @param {string} userId 
     * @throws {RequiredError}
     * @memberof ProjectRouteApiInterface
     */
    projectRequestOpts(requestParameters: ProjectRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} about 
     * @param {string} audio 
     * @param {Array<AudioLine>} audioLines 
     * @param {Array<Faq>} faqs 
     * @param {string} genre 
     * @param {string} id 
     * @param {string} playlist 
     * @param {Array<Season>} seasons 
     * @param {string} summary 
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectRouteApiInterface
     */
    projectRaw(requestParameters: ProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Project>>;

    /**
     */
    project(requestParameters: ProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Project>;

}

/**
 * 
 */
export class ProjectRouteApi extends runtime.BaseAPI implements ProjectRouteApiInterface {

    /**
     * Creates request options for project without sending the request
     */
    async projectRequestOpts(requestParameters: ProjectRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['about'] == null) {
            throw new runtime.RequiredError(
                'about',
                'Required parameter "about" was null or undefined when calling project().'
            );
        }

        if (requestParameters['audio'] == null) {
            throw new runtime.RequiredError(
                'audio',
                'Required parameter "audio" was null or undefined when calling project().'
            );
        }

        if (requestParameters['audioLines'] == null) {
            throw new runtime.RequiredError(
                'audioLines',
                'Required parameter "audioLines" was null or undefined when calling project().'
            );
        }

        if (requestParameters['faqs'] == null) {
            throw new runtime.RequiredError(
                'faqs',
                'Required parameter "faqs" was null or undefined when calling project().'
            );
        }

        if (requestParameters['genre'] == null) {
            throw new runtime.RequiredError(
                'genre',
                'Required parameter "genre" was null or undefined when calling project().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling project().'
            );
        }

        if (requestParameters['playlist'] == null) {
            throw new runtime.RequiredError(
                'playlist',
                'Required parameter "playlist" was null or undefined when calling project().'
            );
        }

        if (requestParameters['seasons'] == null) {
            throw new runtime.RequiredError(
                'seasons',
                'Required parameter "seasons" was null or undefined when calling project().'
            );
        }

        if (requestParameters['summary'] == null) {
            throw new runtime.RequiredError(
                'summary',
                'Required parameter "summary" was null or undefined when calling project().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling project().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        // use FormData when the endpoint consumes multipart/form-data, URLSearchParams otherwise
        const useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['about'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'about', requestParameters['about']);
        }

        if (requestParameters['audio'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'audio', requestParameters['audio']);
        }

        if (requestParameters['audioLines'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'audio_lines', requestParameters['audioLines']!.map(AudioLineToJSON));
        }

        if (requestParameters['faqs'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'faqs', requestParameters['faqs']!.map(FaqToJSON));
        }

        if (requestParameters['genre'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'genre', requestParameters['genre']);
        }

        if (requestParameters['id'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'id', requestParameters['id']);
        }

        if (requestParameters['playlist'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'playlist', requestParameters['playlist']);
        }

        if (requestParameters['seasons'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'seasons', requestParameters['seasons']!.map(SeasonToJSON));
        }

        if (requestParameters['summary'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'summary', requestParameters['summary']);
        }

        if (requestParameters['userId'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'user_id', requestParameters['userId']);
        }


        let urlPath = `/project`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     */
    async projectRaw(requestParameters: ProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Project>> {
        const requestOptions = await this.projectRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectFromJSON(jsonValue));
    }

    /**
     */
    async project(requestParameters: ProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Project> {
        const response = await this.projectRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
