/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { appendBracket } from '../runtime';
import {
    type Solana,
    SolanaFromJSON,
    SolanaToJSON,
} from '../models/Solana';
import {
    type Status,
    StatusFromJSON,
    StatusToJSON,
} from '../models/Status';

export interface SolanaRequest {
    amountCents: number;
    id: string;
    pubkey: string;
    status: Status;
    userId: string;
    credit?: number;
    loaded?: boolean;
    quotedOutUnits?: number;
    requestId?: string | null;
    signature?: string | null;
    signedTx?: string | null;
    unsignedTx?: string | null;
}

/**
 * SolanaRouteApi - interface
 * 
 * @export
 * @interface SolanaRouteApiInterface
 */
export interface SolanaRouteApiInterface {
    /**
     * Creates request options for solana without sending the request
     * @param {number} amountCents 
     * @param {string} id 
     * @param {string} pubkey 
     * @param {Status} status 
     * @param {string} userId 
     * @param {number} [credit] 
     * @param {boolean} [loaded] 
     * @param {number} [quotedOutUnits] 
     * @param {string} [requestId] 
     * @param {string} [signature] 
     * @param {string} [signedTx] 
     * @param {string} [unsignedTx] 
     * @throws {RequiredError}
     * @memberof SolanaRouteApiInterface
     */
    solanaRequestOpts(requestParameters: SolanaRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} amountCents 
     * @param {string} id 
     * @param {string} pubkey 
     * @param {Status} status 
     * @param {string} userId 
     * @param {number} [credit] 
     * @param {boolean} [loaded] 
     * @param {number} [quotedOutUnits] 
     * @param {string} [requestId] 
     * @param {string} [signature] 
     * @param {string} [signedTx] 
     * @param {string} [unsignedTx] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaRouteApiInterface
     */
    solanaRaw(requestParameters: SolanaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Solana>>;

    /**
     */
    solana(requestParameters: SolanaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Solana>;

}

/**
 * 
 */
export class SolanaRouteApi extends runtime.BaseAPI implements SolanaRouteApiInterface {

    /**
     * Creates request options for solana without sending the request
     */
    async solanaRequestOpts(requestParameters: SolanaRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['amountCents'] == null) {
            throw new runtime.RequiredError(
                'amountCents',
                'Required parameter "amountCents" was null or undefined when calling solana().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling solana().'
            );
        }

        if (requestParameters['pubkey'] == null) {
            throw new runtime.RequiredError(
                'pubkey',
                'Required parameter "pubkey" was null or undefined when calling solana().'
            );
        }

        if (requestParameters['status'] == null) {
            throw new runtime.RequiredError(
                'status',
                'Required parameter "status" was null or undefined when calling solana().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling solana().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        // use FormData when the endpoint consumes multipart/form-data, URLSearchParams otherwise
        const useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['amountCents'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'amount_cents', requestParameters['amountCents']);
        }

        if (requestParameters['credit'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'credit', requestParameters['credit']);
        }

        if (requestParameters['id'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'id', requestParameters['id']);
        }

        if (requestParameters['loaded'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'loaded', requestParameters['loaded']);
        }

        if (requestParameters['pubkey'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'pubkey', requestParameters['pubkey']);
        }

        if (requestParameters['quotedOutUnits'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'quoted_out_units', requestParameters['quotedOutUnits']);
        }

        if (requestParameters['requestId'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'request_id', requestParameters['requestId']);
        }

        if (requestParameters['signature'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'signature', requestParameters['signature']);
        }

        if (requestParameters['signedTx'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'signed_tx', requestParameters['signedTx']);
        }

        if (requestParameters['status'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'status', StatusToJSON(requestParameters['status']));
        }

        if (requestParameters['unsignedTx'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'unsigned_tx', requestParameters['unsignedTx']);
        }

        if (requestParameters['userId'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'user_id', requestParameters['userId']);
        }


        let urlPath = `/solana`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     */
    async solanaRaw(requestParameters: SolanaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Solana>> {
        const requestOptions = await this.solanaRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SolanaFromJSON(jsonValue));
    }

    /**
     */
    async solana(requestParameters: SolanaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Solana> {
        const response = await this.solanaRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
