/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { appendBracket } from '../runtime';
import {
    type Model,
    ModelFromJSON,
    ModelToJSON,
} from '../models/Model';
import {
    type Status,
    StatusFromJSON,
    StatusToJSON,
} from '../models/Status';

export interface StripeRequest {
    amountCents: number;
    id: string;
    status: Status;
    userId: string;
    credit?: number;
    loaded?: boolean;
    paymentUrl?: string | null;
    stripePaymentIntentId?: string | null;
    stripeSessionId?: string | null;
}

/**
 * StripeRouteApi - interface
 * 
 * @export
 * @interface StripeRouteApiInterface
 */
export interface StripeRouteApiInterface {
    /**
     * Creates request options for stripe without sending the request
     * @param {number} amountCents 
     * @param {string} id 
     * @param {Status} status 
     * @param {string} userId 
     * @param {number} [credit] 
     * @param {boolean} [loaded] 
     * @param {string} [paymentUrl] 
     * @param {string} [stripePaymentIntentId] 
     * @param {string} [stripeSessionId] 
     * @throws {RequiredError}
     * @memberof StripeRouteApiInterface
     */
    stripeRequestOpts(requestParameters: StripeRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} amountCents 
     * @param {string} id 
     * @param {Status} status 
     * @param {string} userId 
     * @param {number} [credit] 
     * @param {boolean} [loaded] 
     * @param {string} [paymentUrl] 
     * @param {string} [stripePaymentIntentId] 
     * @param {string} [stripeSessionId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StripeRouteApiInterface
     */
    stripeRaw(requestParameters: StripeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Model>>;

    /**
     */
    stripe(requestParameters: StripeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Model>;

}

/**
 * 
 */
export class StripeRouteApi extends runtime.BaseAPI implements StripeRouteApiInterface {

    /**
     * Creates request options for stripe without sending the request
     */
    async stripeRequestOpts(requestParameters: StripeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['amountCents'] == null) {
            throw new runtime.RequiredError(
                'amountCents',
                'Required parameter "amountCents" was null or undefined when calling stripe().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling stripe().'
            );
        }

        if (requestParameters['status'] == null) {
            throw new runtime.RequiredError(
                'status',
                'Required parameter "status" was null or undefined when calling stripe().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling stripe().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        // use FormData when the endpoint consumes multipart/form-data, URLSearchParams otherwise
        const useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['amountCents'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'amount_cents', requestParameters['amountCents']);
        }

        if (requestParameters['credit'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'credit', requestParameters['credit']);
        }

        if (requestParameters['id'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'id', requestParameters['id']);
        }

        if (requestParameters['loaded'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'loaded', requestParameters['loaded']);
        }

        if (requestParameters['paymentUrl'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'payment_url', requestParameters['paymentUrl']);
        }

        if (requestParameters['status'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'status', StatusToJSON(requestParameters['status']));
        }

        if (requestParameters['stripePaymentIntentId'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'stripe_payment_intent_id', requestParameters['stripePaymentIntentId']);
        }

        if (requestParameters['stripeSessionId'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'stripe_session_id', requestParameters['stripeSessionId']);
        }

        if (requestParameters['userId'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'user_id', requestParameters['userId']);
        }


        let urlPath = `/stripe`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     */
    async stripeRaw(requestParameters: StripeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Model>> {
        const requestOptions = await this.stripeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelFromJSON(jsonValue));
    }

    /**
     */
    async stripe(requestParameters: StripeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Model> {
        const response = await this.stripeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
