/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { appendBracket } from '../runtime';
import {
    type Upload,
    UploadFromJSON,
    UploadToJSON,
} from '../models/Upload';

export interface UploadRequest {
    credit: number;
    file: string;
    id: string;
    userId: string;
}

/**
 * UploadRouteApi - interface
 * 
 * @export
 * @interface UploadRouteApiInterface
 */
export interface UploadRouteApiInterface {
    /**
     * Creates request options for upload without sending the request
     * @param {number} credit 
     * @param {string} file 
     * @param {string} id uuid v7
     * @param {string} userId 
     * @throws {RequiredError}
     * @memberof UploadRouteApiInterface
     */
    uploadRequestOpts(requestParameters: UploadRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} credit 
     * @param {string} file 
     * @param {string} id uuid v7
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UploadRouteApiInterface
     */
    uploadRaw(requestParameters: UploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Upload>>;

    /**
     */
    upload(requestParameters: UploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Upload>;

}

/**
 * 
 */
export class UploadRouteApi extends runtime.BaseAPI implements UploadRouteApiInterface {

    /**
     * Creates request options for upload without sending the request
     */
    async uploadRequestOpts(requestParameters: UploadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['credit'] == null) {
            throw new runtime.RequiredError(
                'credit',
                'Required parameter "credit" was null or undefined when calling upload().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling upload().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling upload().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling upload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        // use FormData when the endpoint consumes multipart/form-data, URLSearchParams otherwise
        const useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['credit'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'credit', requestParameters['credit']);
        }

        if (requestParameters['file'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'file', requestParameters['file']);
        }

        if (requestParameters['id'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'id', requestParameters['id']);
        }

        if (requestParameters['userId'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'user_id', requestParameters['userId']);
        }


        let urlPath = `/upload`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     */
    async uploadRaw(requestParameters: UploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Upload>> {
        const requestOptions = await this.uploadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadFromJSON(jsonValue));
    }

    /**
     */
    async upload(requestParameters: UploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Upload> {
        const response = await this.uploadRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
