/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { appendBracket } from '../runtime';
import {
    type Status,
    StatusFromJSON,
    StatusToJSON,
} from '../models/Status';
import {
    type Wise,
    WiseFromJSON,
    WiseToJSON,
} from '../models/Wise';

export interface WiseCheckRequest {
    amountCents: number;
    currency: string;
    id: string;
    reference: string;
    status: Status;
    userId: string;
    credit?: number;
    loaded?: boolean;
    wiseCreditId?: string | null;
}

/**
 * WiseApi - interface
 * 
 * @export
 * @interface WiseApiInterface
 */
export interface WiseApiInterface {
    /**
     * Creates request options for wiseCheck without sending the request
     * @param {number} amountCents 
     * @param {string} currency 
     * @param {string} id 
     * @param {string} reference 
     * @param {Status} status 
     * @param {string} userId 
     * @param {number} [credit] 
     * @param {boolean} [loaded] 
     * @param {string} [wiseCreditId] 
     * @throws {RequiredError}
     * @memberof WiseApiInterface
     */
    wiseCheckRequestOpts(requestParameters: WiseCheckRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} amountCents 
     * @param {string} currency 
     * @param {string} id 
     * @param {string} reference 
     * @param {Status} status 
     * @param {string} userId 
     * @param {number} [credit] 
     * @param {boolean} [loaded] 
     * @param {string} [wiseCreditId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WiseApiInterface
     */
    wiseCheckRaw(requestParameters: WiseCheckRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Wise>>;

    /**
     */
    wiseCheck(requestParameters: WiseCheckRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Wise>;

}

/**
 * 
 */
export class WiseApi extends runtime.BaseAPI implements WiseApiInterface {

    /**
     * Creates request options for wiseCheck without sending the request
     */
    async wiseCheckRequestOpts(requestParameters: WiseCheckRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['amountCents'] == null) {
            throw new runtime.RequiredError(
                'amountCents',
                'Required parameter "amountCents" was null or undefined when calling wiseCheck().'
            );
        }

        if (requestParameters['currency'] == null) {
            throw new runtime.RequiredError(
                'currency',
                'Required parameter "currency" was null or undefined when calling wiseCheck().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling wiseCheck().'
            );
        }

        if (requestParameters['reference'] == null) {
            throw new runtime.RequiredError(
                'reference',
                'Required parameter "reference" was null or undefined when calling wiseCheck().'
            );
        }

        if (requestParameters['status'] == null) {
            throw new runtime.RequiredError(
                'status',
                'Required parameter "status" was null or undefined when calling wiseCheck().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling wiseCheck().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        // use FormData when the endpoint consumes multipart/form-data, URLSearchParams otherwise
        const useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['amountCents'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'amount_cents', requestParameters['amountCents']);
        }

        if (requestParameters['credit'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'credit', requestParameters['credit']);
        }

        if (requestParameters['currency'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'currency', requestParameters['currency']);
        }

        if (requestParameters['id'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'id', requestParameters['id']);
        }

        if (requestParameters['loaded'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'loaded', requestParameters['loaded']);
        }

        if (requestParameters['reference'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'reference', requestParameters['reference']);
        }

        if (requestParameters['status'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'status', StatusToJSON(requestParameters['status']));
        }

        if (requestParameters['userId'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'user_id', requestParameters['userId']);
        }

        if (requestParameters['wiseCreditId'] != null) {
            appendBracket(formParams as FormData | URLSearchParams, 'wise_credit_id', requestParameters['wiseCreditId']);
        }


        let urlPath = `/wise_check`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     */
    async wiseCheckRaw(requestParameters: WiseCheckRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Wise>> {
        const requestOptions = await this.wiseCheckRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WiseFromJSON(jsonValue));
    }

    /**
     */
    async wiseCheck(requestParameters: WiseCheckRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Wise> {
        const response = await this.wiseCheckRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
