/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiAiModel } from './ApiAiModel';
import {
    ApiAiModelFromJSON,
    ApiAiModelFromJSONTyped,
    ApiAiModelToJSON,
    ApiAiModelToJSONTyped,
} from './ApiAiModel';
import type { ApiAction } from './ApiAction';
import {
    ApiActionFromJSON,
    ApiActionFromJSONTyped,
    ApiActionToJSON,
    ApiActionToJSONTyped,
} from './ApiAction';
import type { ApiPay } from './ApiPay';
import {
    ApiPayFromJSON,
    ApiPayFromJSONTyped,
    ApiPayToJSON,
    ApiPayToJSONTyped,
} from './ApiPay';
import type { ApiStatus } from './ApiStatus';
import {
    ApiStatusFromJSON,
    ApiStatusFromJSONTyped,
    ApiStatusToJSON,
    ApiStatusToJSONTyped,
} from './ApiStatus';
import type { ApiChatMessage } from './ApiChatMessage';
import {
    ApiChatMessageFromJSON,
    ApiChatMessageFromJSONTyped,
    ApiChatMessageToJSON,
    ApiChatMessageToJSONTyped,
} from './ApiChatMessage';

/**
 * default values
 * @export
 * @interface API
 */
export interface API {
    /**
     * 
     * @type {ApiAction}
     * @memberof API
     */
    action: ApiAction;
    /**
     * input audio as base64 — data URI (web) or raw base64 (android/ios), empty if unused; type detected server-side
     * @type {string}
     * @memberof API
     */
    audio: string;
    /**
     * 
     * @type {number}
     * @memberof API
     */
    balance: number;
    /**
     * 
     * @type {number}
     * @memberof API
     */
    credit: number;
    /**
     * filename of result to retrieve
     * @type {string}
     * @memberof API
     */
    file: string;
    /**
     * uuid v7
     * @type {string}
     * @memberof API
     */
    id: string;
    /**
     * input image as base64 — data URI (web) or raw base64 (android/ios), empty if unused; type detected server-side
     * @type {string}
     * @memberof API
     */
    image: string;
    /**
     * default value is non-empty array
     * @type {Array<ApiChatMessage>}
     * @memberof API
     */
    messages: Array<ApiChatMessage>;
    /**
     * 
     * @type {ApiAiModel}
     * @memberof API
     */
    model: ApiAiModel;
    /**
     * 
     * @type {ApiPay}
     * @memberof API
     */
    pay: ApiPay;
    /**
     * 
     * @type {string}
     * @memberof API
     */
    prompt: string;
    /**
     * transient, managed by server
     * @type {string}
     * @memberof API
     */
    requestId: string;
    /**
     * 
     * @type {ApiStatus}
     * @memberof API
     */
    status: ApiStatus;
    /**
     * 
     * @type {string}
     * @memberof API
     */
    userId: string;
}



/**
 * Check if a given object implements the API interface.
 */
export function instanceOfAPI(value: object): value is API {
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('audio' in value) || value['audio'] === undefined) return false;
    if (!('balance' in value) || value['balance'] === undefined) return false;
    if (!('credit' in value) || value['credit'] === undefined) return false;
    if (!('file' in value) || value['file'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('messages' in value) || value['messages'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('pay' in value) || value['pay'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function APIFromJSON(json: any): API {
    return APIFromJSONTyped(json, false);
}

export function APIFromJSONTyped(json: any, ignoreDiscriminator: boolean): API {
    if (json == null) {
        return json;
    }
    return {
        
        'action': ApiActionFromJSON(json['action']),
        'audio': json['audio'],
        'balance': json['balance'],
        'credit': json['credit'],
        'file': json['file'],
        'id': json['id'],
        'image': json['image'],
        'messages': ((json['messages'] as Array<any>).map(ApiChatMessageFromJSON)),
        'model': ApiAiModelFromJSON(json['model']),
        'pay': ApiPayFromJSON(json['pay']),
        'prompt': json['prompt'],
        'requestId': json['request_id'],
        'status': ApiStatusFromJSON(json['status']),
        'userId': json['user_id'],
    };
}

export function APIToJSON(json: any): API {
    return APIToJSONTyped(json, false);
}

export function APIToJSONTyped(value?: API | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': ApiActionToJSON(value['action']),
        'audio': value['audio'],
        'balance': value['balance'],
        'credit': value['credit'],
        'file': value['file'],
        'id': value['id'],
        'image': value['image'],
        'messages': ((value['messages'] as Array<any>).map(ApiChatMessageToJSON)),
        'model': ApiAiModelToJSON(value['model']),
        'pay': ApiPayToJSON(value['pay']),
        'prompt': value['prompt'],
        'request_id': value['requestId'],
        'status': ApiStatusToJSON(value['status']),
        'user_id': value['userId'],
    };
}

