/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiAction } from './ApiAction';
import {
    ApiActionFromJSON,
    ApiActionFromJSONTyped,
    ApiActionToJSON,
    ApiActionToJSONTyped,
} from './ApiAction';
import type { ApiStatus } from './ApiStatus';
import {
    ApiStatusFromJSON,
    ApiStatusFromJSONTyped,
    ApiStatusToJSON,
    ApiStatusToJSONTyped,
} from './ApiStatus';

/**
 * default values
 * @export
 * @interface API
 */
export interface API {
    /**
     * 
     * @type {ApiAction}
     * @memberof API
     */
    action: ApiAction;
    /**
     * return only
     * @type {number}
     * @memberof API
     */
    credit: number;
    /**
     * uuid v7 preferred
     * @type {string}
     * @memberof API
     */
    id: string;
    /**
     * 
     * @type {ApiStatus}
     * @memberof API
     */
    status: ApiStatus;
    /**
     * 
     * @type {string}
     * @memberof API
     */
    userId: string;
}



/**
 * Check if a given object implements the API interface.
 */
export function instanceOfAPI(value: object): value is API {
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('credit' in value) || value['credit'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function APIFromJSON(json: any): API {
    return APIFromJSONTyped(json, false);
}

export function APIFromJSONTyped(json: any, ignoreDiscriminator: boolean): API {
    if (json == null) {
        return json;
    }
    return {
        
        'action': ApiActionFromJSON(json['action']),
        'credit': json['credit'],
        'id': json['id'],
        'status': ApiStatusFromJSON(json['status']),
        'userId': json['user_id'],
    };
}

export function APIToJSON(json: any): API {
    return APIToJSONTyped(json, false);
}

export function APIToJSONTyped(value?: API | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': ApiActionToJSON(value['action']),
        'credit': value['credit'],
        'id': value['id'],
        'status': ApiStatusToJSON(value['status']),
        'user_id': value['userId'],
    };
}

