/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ApiAction {
    Generate = 'Generate',
    Poll = 'Poll',
    Pay = 'Pay',
    Chat = 'Chat',
    Balance = 'Balance',
    Pricing = 'Pricing'
}


export function instanceOfApiAction(value: any): boolean {
    for (const key in ApiAction) {
        if (Object.prototype.hasOwnProperty.call(ApiAction, key)) {
            if (ApiAction[key as keyof typeof ApiAction] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApiActionFromJSON(json: any): ApiAction {
    return ApiActionFromJSONTyped(json, false);
}

export function ApiActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAction {
    return json as ApiAction;
}

export function ApiActionToJSON(value?: ApiAction | null): any {
    return value as any;
}

export function ApiActionToJSONTyped(value: any, ignoreDiscriminator: boolean): ApiAction {
    return value as ApiAction;
}

