/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ApplePay } from './ApplePay';
import {
    instanceOfApplePay,
    ApplePayFromJSON,
    ApplePayFromJSONTyped,
    ApplePayToJSON,
} from './ApplePay';
import type { Charge } from './Charge';
import {
    instanceOfCharge,
    ChargeFromJSON,
    ChargeFromJSONTyped,
    ChargeToJSON,
} from './Charge';
import type { ClaudeSonnet46 } from './ClaudeSonnet46';
import {
    instanceOfClaudeSonnet46,
    ClaudeSonnet46FromJSON,
    ClaudeSonnet46FromJSONTyped,
    ClaudeSonnet46ToJSON,
} from './ClaudeSonnet46';
import type { Flux2DevI2I } from './Flux2DevI2I';
import {
    instanceOfFlux2DevI2I,
    Flux2DevI2IFromJSON,
    Flux2DevI2IFromJSONTyped,
    Flux2DevI2IToJSON,
} from './Flux2DevI2I';
import type { Flux2KleinI2I } from './Flux2KleinI2I';
import {
    instanceOfFlux2KleinI2I,
    Flux2KleinI2IFromJSON,
    Flux2KleinI2IFromJSONTyped,
    Flux2KleinI2IToJSON,
} from './Flux2KleinI2I';
import type { Flux2Pro } from './Flux2Pro';
import {
    instanceOfFlux2Pro,
    Flux2ProFromJSON,
    Flux2ProFromJSONTyped,
    Flux2ProToJSON,
} from './Flux2Pro';
import type { GooglePay } from './GooglePay';
import {
    instanceOfGooglePay,
    GooglePayFromJSON,
    GooglePayFromJSONTyped,
    GooglePayToJSON,
} from './GooglePay';
import type { Ltx23A2V } from './Ltx23A2V';
import {
    instanceOfLtx23A2V,
    Ltx23A2VFromJSON,
    Ltx23A2VFromJSONTyped,
    Ltx23A2VToJSON,
} from './Ltx23A2V';
import type { LyricSync } from './LyricSync';
import {
    instanceOfLyricSync,
    LyricSyncFromJSON,
    LyricSyncFromJSONTyped,
    LyricSyncToJSON,
} from './LyricSync';
import type { NanoBanana2 } from './NanoBanana2';
import {
    instanceOfNanoBanana2,
    NanoBanana2FromJSON,
    NanoBanana2FromJSONTyped,
    NanoBanana2ToJSON,
} from './NanoBanana2';
import type { Stripe } from './Stripe';
import {
    instanceOfStripe,
    StripeFromJSON,
    StripeFromJSONTyped,
    StripeToJSON,
} from './Stripe';
import type { ZImageTurbo } from './ZImageTurbo';
import {
    instanceOfZImageTurbo,
    ZImageTurboFromJSON,
    ZImageTurboFromJSONTyped,
    ZImageTurboToJSON,
} from './ZImageTurbo';

/**
 * @type ApiAction
 * 
 * @export
 */
export type ApiAction = { type: 'ApplePay' } & ApplePay | { type: 'Charge' } & Charge | { type: 'ClaudeSonnet4_6' } & ClaudeSonnet46 | { type: 'Flux2DevI2I' } & Flux2DevI2I | { type: 'Flux2KleinI2I' } & Flux2KleinI2I | { type: 'Flux2Pro' } & Flux2Pro | { type: 'GooglePay' } & GooglePay | { type: 'Ltx2_3A2V' } & Ltx23A2V | { type: 'LyricSync' } & LyricSync | { type: 'NanoBanana2' } & NanoBanana2 | { type: 'Stripe' } & Stripe | { type: 'ZImageTurbo' } & ZImageTurbo;

export function ApiActionFromJSON(json: any): ApiAction {
    return ApiActionFromJSONTyped(json, false);
}

export function ApiActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAction {
    if (json == null) {
        return json;
    }
    switch (json['type']) {
        case 'ApplePay':
            return Object.assign({}, ApplePayFromJSONTyped(json, true), { type: 'ApplePay' } as const);
        case 'Charge':
            return Object.assign({}, ChargeFromJSONTyped(json, true), { type: 'Charge' } as const);
        case 'ClaudeSonnet4_6':
            return Object.assign({}, ClaudeSonnet46FromJSONTyped(json, true), { type: 'ClaudeSonnet4_6' } as const);
        case 'Flux2DevI2I':
            return Object.assign({}, Flux2DevI2IFromJSONTyped(json, true), { type: 'Flux2DevI2I' } as const);
        case 'Flux2KleinI2I':
            return Object.assign({}, Flux2KleinI2IFromJSONTyped(json, true), { type: 'Flux2KleinI2I' } as const);
        case 'Flux2Pro':
            return Object.assign({}, Flux2ProFromJSONTyped(json, true), { type: 'Flux2Pro' } as const);
        case 'GooglePay':
            return Object.assign({}, GooglePayFromJSONTyped(json, true), { type: 'GooglePay' } as const);
        case 'Ltx2_3A2V':
            return Object.assign({}, Ltx23A2VFromJSONTyped(json, true), { type: 'Ltx2_3A2V' } as const);
        case 'LyricSync':
            return Object.assign({}, LyricSyncFromJSONTyped(json, true), { type: 'LyricSync' } as const);
        case 'NanoBanana2':
            return Object.assign({}, NanoBanana2FromJSONTyped(json, true), { type: 'NanoBanana2' } as const);
        case 'Stripe':
            return Object.assign({}, StripeFromJSONTyped(json, true), { type: 'Stripe' } as const);
        case 'ZImageTurbo':
            return Object.assign({}, ZImageTurboFromJSONTyped(json, true), { type: 'ZImageTurbo' } as const);
        default:
            return json;
    }
}

export function ApiActionToJSON(json: any): any {
    return ApiActionToJSONTyped(json, false);
}

export function ApiActionToJSONTyped(value?: ApiAction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'ApplePay':
            return Object.assign({}, ApplePayToJSON(value), { type: 'ApplePay' } as const);
        case 'Charge':
            return Object.assign({}, ChargeToJSON(value), { type: 'Charge' } as const);
        case 'ClaudeSonnet4_6':
            return Object.assign({}, ClaudeSonnet46ToJSON(value), { type: 'ClaudeSonnet4_6' } as const);
        case 'Flux2DevI2I':
            return Object.assign({}, Flux2DevI2IToJSON(value), { type: 'Flux2DevI2I' } as const);
        case 'Flux2KleinI2I':
            return Object.assign({}, Flux2KleinI2IToJSON(value), { type: 'Flux2KleinI2I' } as const);
        case 'Flux2Pro':
            return Object.assign({}, Flux2ProToJSON(value), { type: 'Flux2Pro' } as const);
        case 'GooglePay':
            return Object.assign({}, GooglePayToJSON(value), { type: 'GooglePay' } as const);
        case 'Ltx2_3A2V':
            return Object.assign({}, Ltx23A2VToJSON(value), { type: 'Ltx2_3A2V' } as const);
        case 'LyricSync':
            return Object.assign({}, LyricSyncToJSON(value), { type: 'LyricSync' } as const);
        case 'NanoBanana2':
            return Object.assign({}, NanoBanana2ToJSON(value), { type: 'NanoBanana2' } as const);
        case 'Stripe':
            return Object.assign({}, StripeToJSON(value), { type: 'Stripe' } as const);
        case 'ZImageTurbo':
            return Object.assign({}, ZImageTurboToJSON(value), { type: 'ZImageTurbo' } as const);
        default:
            return value;
    }
}

