/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ApiAiModel {
    ZImageTurbo = 'ZImageTurbo',
    NanoBanana2 = 'NanoBanana2',
    Flux2Pro = 'Flux2Pro',
    Ltx23A2V = 'Ltx2_3A2V',
    NgrokText = 'NgrokText'
}


export function instanceOfApiAiModel(value: any): boolean {
    for (const key in ApiAiModel) {
        if (Object.prototype.hasOwnProperty.call(ApiAiModel, key)) {
            if (ApiAiModel[key as keyof typeof ApiAiModel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApiAiModelFromJSON(json: any): ApiAiModel {
    return ApiAiModelFromJSONTyped(json, false);
}

export function ApiAiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAiModel {
    return json as ApiAiModel;
}

export function ApiAiModelToJSON(value?: ApiAiModel | null): any {
    return value as any;
}

export function ApiAiModelToJSONTyped(value: any, ignoreDiscriminator: boolean): ApiAiModel {
    return value as ApiAiModel;
}

