/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ApiChatRole {
    User = 'User',
    Assistant = 'Assistant'
}


export function instanceOfApiChatRole(value: any): boolean {
    for (const key in ApiChatRole) {
        if (Object.prototype.hasOwnProperty.call(ApiChatRole, key)) {
            if (ApiChatRole[key as keyof typeof ApiChatRole] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApiChatRoleFromJSON(json: any): ApiChatRole {
    return ApiChatRoleFromJSONTyped(json, false);
}

export function ApiChatRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiChatRole {
    return json as ApiChatRole;
}

export function ApiChatRoleToJSON(value?: ApiChatRole | null): any {
    return value as any;
}

export function ApiChatRoleToJSONTyped(value: any, ignoreDiscriminator: boolean): ApiChatRole {
    return value as ApiChatRole;
}

