/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiChatRole } from './ApiChatRole';
import {
    ApiChatRoleFromJSON,
    ApiChatRoleFromJSONTyped,
    ApiChatRoleToJSON,
    ApiChatRoleToJSONTyped,
} from './ApiChatRole';

/**
 * 
 * @export
 * @interface ApiChatMessage
 */
export interface ApiChatMessage {
    /**
     * 
     * @type {string}
     * @memberof ApiChatMessage
     */
    content: string;
    /**
     * 
     * @type {ApiChatRole}
     * @memberof ApiChatMessage
     */
    role: ApiChatRole;
}



/**
 * Check if a given object implements the ApiChatMessage interface.
 */
export function instanceOfApiChatMessage(value: object): value is ApiChatMessage {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function ApiChatMessageFromJSON(json: any): ApiChatMessage {
    return ApiChatMessageFromJSONTyped(json, false);
}

export function ApiChatMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiChatMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'role': ApiChatRoleFromJSON(json['role']),
    };
}

export function ApiChatMessageToJSON(json: any): ApiChatMessage {
    return ApiChatMessageToJSONTyped(json, false);
}

export function ApiChatMessageToJSONTyped(value?: ApiChatMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'role': ApiChatRoleToJSON(value['role']),
    };
}

