/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiPayProvider } from './ApiPayProvider';
import {
    ApiPayProviderFromJSON,
    ApiPayProviderFromJSONTyped,
    ApiPayProviderToJSON,
    ApiPayProviderToJSONTyped,
} from './ApiPayProvider';

/**
 * default values
 * @export
 * @interface ApiPay
 */
export interface ApiPay {
    /**
     * 
     * @type {string}
     * @memberof ApiPay
     */
    currency: string;
    /**
     * uuid v7
     * @type {string}
     * @memberof ApiPay
     */
    id: string;
    /**
     * Signed transaction JWS from StoreKit; the input to Apple verification.
     * @type {string}
     * @memberof ApiPay
     */
    jws: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApiPay
     */
    loaded: boolean;
    /**
     * Google's per-purchase `orderId`, returned by the Play Developer API (not
     * the client). Not used for dedup — `ref_id` is — because promo-code
     * purchases may have no `orderId`.
     * On the Stripe path, the same field carries the `payment_intent` id
     * returned by `checkout.session.completed`.
     * @type {string}
     * @memberof ApiPay
     */
    orderId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiPay
     */
    packageName: string;
    /**
     * Stripe only. Hosted-payment URL returned by `checkout.sessions.create` —
     * empty until the server creates the session.
     * @type {string}
     * @memberof ApiPay
     */
    paymentUrl: string;
    /**
     * 
     * @type {number}
     * @memberof ApiPay
     */
    price: number;
    /**
     * 
     * @type {string}
     * @memberof ApiPay
     */
    productId: string;
    /**
     * Selects the verification path: Apple App Store vs Google Play.
     * @type {ApiPayProvider}
     * @memberof ApiPay
     */
    provider: ApiPayProvider;
    /**
     * Globally-unique purchase id, used as the idempotency key for both stores.
     * Apple: the `transactionId`, extracted server-side from the verified JWS
     *   (empty on the incoming request — the server fills it in).
     * Google: the `purchaseToken`, sent by the client. It is both the input to
     *   Play Developer API verification and the idempotency key.
     * @type {string}
     * @memberof ApiPay
     */
    refId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPay
     */
    userId: string;
}



/**
 * Check if a given object implements the ApiPay interface.
 */
export function instanceOfApiPay(value: object): value is ApiPay {
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('jws' in value) || value['jws'] === undefined) return false;
    if (!('loaded' in value) || value['loaded'] === undefined) return false;
    if (!('packageName' in value) || value['packageName'] === undefined) return false;
    if (!('paymentUrl' in value) || value['paymentUrl'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('refId' in value) || value['refId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function ApiPayFromJSON(json: any): ApiPay {
    return ApiPayFromJSONTyped(json, false);
}

export function ApiPayFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiPay {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'],
        'id': json['id'],
        'jws': json['jws'],
        'loaded': json['loaded'],
        'orderId': json['order_id'] == null ? undefined : json['order_id'],
        'packageName': json['package_name'],
        'paymentUrl': json['payment_url'],
        'price': json['price'],
        'productId': json['product_id'],
        'provider': ApiPayProviderFromJSON(json['provider']),
        'refId': json['ref_id'],
        'userId': json['user_id'],
    };
}

export function ApiPayToJSON(json: any): ApiPay {
    return ApiPayToJSONTyped(json, false);
}

export function ApiPayToJSONTyped(value?: ApiPay | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'id': value['id'],
        'jws': value['jws'],
        'loaded': value['loaded'],
        'order_id': value['orderId'],
        'package_name': value['packageName'],
        'payment_url': value['paymentUrl'],
        'price': value['price'],
        'product_id': value['productId'],
        'provider': ApiPayProviderToJSON(value['provider']),
        'ref_id': value['refId'],
        'user_id': value['userId'],
    };
}

