/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ApiPayProvider {
    Apple = 'Apple',
    Google = 'Google'
}


export function instanceOfApiPayProvider(value: any): boolean {
    for (const key in ApiPayProvider) {
        if (Object.prototype.hasOwnProperty.call(ApiPayProvider, key)) {
            if (ApiPayProvider[key as keyof typeof ApiPayProvider] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApiPayProviderFromJSON(json: any): ApiPayProvider {
    return ApiPayProviderFromJSONTyped(json, false);
}

export function ApiPayProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiPayProvider {
    return json as ApiPayProvider;
}

export function ApiPayProviderToJSON(value?: ApiPayProvider | null): any {
    return value as any;
}

export function ApiPayProviderToJSONTyped(value: any, ignoreDiscriminator: boolean): ApiPayProvider {
    return value as ApiPayProvider;
}

