/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ApiStatus {
    Pending = 'Pending',
    Completed = 'Completed',
    Failed = 'Failed'
}


export function instanceOfApiStatus(value: any): boolean {
    for (const key in ApiStatus) {
        if (Object.prototype.hasOwnProperty.call(ApiStatus, key)) {
            if (ApiStatus[key as keyof typeof ApiStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApiStatusFromJSON(json: any): ApiStatus {
    return ApiStatusFromJSONTyped(json, false);
}

export function ApiStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiStatus {
    return json as ApiStatus;
}

export function ApiStatusToJSON(value?: ApiStatus | null): any {
    return value as any;
}

export function ApiStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ApiStatus {
    return value as ApiStatus;
}

