/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApplePayStatus } from './ApplePayStatus';
import {
    ApplePayStatusFromJSON,
    ApplePayStatusFromJSONTyped,
    ApplePayStatusToJSON,
    ApplePayStatusToJSONTyped,
} from './ApplePayStatus';

/**
 * Put default values
 * @export
 * @interface ApplePay
 */
export interface ApplePay {
    /**
     * 
     * @type {number}
     * @memberof ApplePay
     */
    credit: number;
    /**
     * 
     * @type {string}
     * @memberof ApplePay
     */
    currency: string;
    /**
     * uuid v7
     * @type {string}
     * @memberof ApplePay
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ApplePay
     */
    jws: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApplePay
     */
    loaded: boolean;
    /**
     * 
     * @type {number}
     * @memberof ApplePay
     */
    price: number;
    /**
     * 
     * @type {string}
     * @memberof ApplePay
     */
    productId: string;
    /**
     * 
     * @type {ApplePayStatus}
     * @memberof ApplePay
     */
    status: ApplePayStatus;
    /**
     * 
     * @type {string}
     * @memberof ApplePay
     */
    transactionId: string;
    /**
     * 
     * @type {string}
     * @memberof ApplePay
     */
    userId: string;
}



/**
 * Check if a given object implements the ApplePay interface.
 */
export function instanceOfApplePay(value: object): value is ApplePay {
    if (!('credit' in value) || value['credit'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('jws' in value) || value['jws'] === undefined) return false;
    if (!('loaded' in value) || value['loaded'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('transactionId' in value) || value['transactionId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function ApplePayFromJSON(json: any): ApplePay {
    return ApplePayFromJSONTyped(json, false);
}

export function ApplePayFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplePay {
    if (json == null) {
        return json;
    }
    return {
        
        'credit': json['credit'],
        'currency': json['currency'],
        'id': json['id'],
        'jws': json['jws'],
        'loaded': json['loaded'],
        'price': json['price'],
        'productId': json['product_id'],
        'status': ApplePayStatusFromJSON(json['status']),
        'transactionId': json['transaction_id'],
        'userId': json['user_id'],
    };
}

export function ApplePayToJSON(json: any): ApplePay {
    return ApplePayToJSONTyped(json, false);
}

export function ApplePayToJSONTyped(value?: ApplePay | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'credit': value['credit'],
        'currency': value['currency'],
        'id': value['id'],
        'jws': value['jws'],
        'loaded': value['loaded'],
        'price': value['price'],
        'product_id': value['productId'],
        'status': ApplePayStatusToJSON(value['status']),
        'transaction_id': value['transactionId'],
        'user_id': value['userId'],
    };
}

