/* tslint:disable */
/* eslint-disable */
/**
 * femi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplePay
 */
export interface ApplePay {
    /**
     * 
     * @type {number}
     * @memberof ApplePay
     */
    credit: number;
    /**
     * 
     * @type {string}
     * @memberof ApplePay
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof ApplePay
     */
    jws: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApplePay
     */
    loaded: boolean;
    /**
     * 
     * @type {number}
     * @memberof ApplePay
     */
    price: number;
    /**
     * 
     * @type {string}
     * @memberof ApplePay
     */
    productId: string;
    /**
     * 
     * @type {string}
     * @memberof ApplePay
     */
    transactionId: string;
    /**
     * 
     * @type {ApplePayTypeEnum}
     * @memberof ApplePay
     */
    type: 'ApplePay';
}




/**
 * Check if a given object implements the ApplePay interface.
 */
export function instanceOfApplePay(value: object): value is ApplePay {
    if (!('credit' in value) || value['credit'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('jws' in value) || value['jws'] === undefined) return false;
    if (!('loaded' in value) || value['loaded'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('transactionId' in value) || value['transactionId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ApplePayFromJSON(json: any): ApplePay {
    return ApplePayFromJSONTyped(json, false);
}

export function ApplePayFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplePay {
    if (json == null) {
        return json;
    }
    return {
        
        'credit': json['credit'],
        'currency': json['currency'],
        'jws': json['jws'],
        'loaded': json['loaded'],
        'price': json['price'],
        'productId': json['product_id'],
        'transactionId': json['transaction_id'],
        'type': json['type'],
    };
}

export function ApplePayToJSON(json: any): ApplePay {
    return ApplePayToJSONTyped(json, false);
}

export function ApplePayToJSONTyped(value?: ApplePay | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'credit': value['credit'],
        'currency': value['currency'],
        'jws': value['jws'],
        'loaded': value['loaded'],
        'price': value['price'],
        'product_id': value['productId'],
        'transaction_id': value['transactionId'],
        'type': value['type'],
    };
}

