/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ApplePayStatus {
    Pending = 'Pending',
    Completed = 'Completed',
    Failed = 'Failed'
}


export function instanceOfApplePayStatus(value: any): boolean {
    for (const key in ApplePayStatus) {
        if (Object.prototype.hasOwnProperty.call(ApplePayStatus, key)) {
            if (ApplePayStatus[key as keyof typeof ApplePayStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApplePayStatusFromJSON(json: any): ApplePayStatus {
    return ApplePayStatusFromJSONTyped(json, false);
}

export function ApplePayStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplePayStatus {
    return json as ApplePayStatus;
}

export function ApplePayStatusToJSON(value?: ApplePayStatus | null): any {
    return value as any;
}

export function ApplePayStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ApplePayStatus {
    return value as ApplePayStatus;
}

