/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AudioLine
 */
export interface AudioLine {
    /**
     * 
     * @type {string}
     * @memberof AudioLine
     */
    context: string;
    /**
     * 
     * @type {string}
     * @memberof AudioLine
     */
    goal: string;
    /**
     * 
     * @type {string}
     * @memberof AudioLine
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AudioLine
     */
    line: string;
    /**
     * 
     * @type {number}
     * @memberof AudioLine
     */
    startTime: number;
}

/**
 * Check if a given object implements the AudioLine interface.
 */
export function instanceOfAudioLine(value: object): value is AudioLine {
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('goal' in value) || value['goal'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('line' in value) || value['line'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    return true;
}

export function AudioLineFromJSON(json: any): AudioLine {
    return AudioLineFromJSONTyped(json, false);
}

export function AudioLineFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioLine {
    if (json == null) {
        return json;
    }
    return {
        
        'context': json['context'],
        'goal': json['goal'],
        'id': json['id'],
        'line': json['line'],
        'startTime': json['start_time'],
    };
}

export function AudioLineToJSON(json: any): AudioLine {
    return AudioLineToJSONTyped(json, false);
}

export function AudioLineToJSONTyped(value?: AudioLine | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': value['context'],
        'goal': value['goal'],
        'id': value['id'],
        'line': value['line'],
        'start_time': value['startTime'],
    };
}

