/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Charge
 */
export interface Charge {
    /**
     * 
     * @type {string}
     * @memberof Charge
     */
    description: string;
    /**
     * 
     * @type {ChargeTypeEnum}
     * @memberof Charge
     */
    type: 'Charge';
}




/**
 * Check if a given object implements the Charge interface.
 */
export function instanceOfCharge(value: object): value is Charge {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ChargeFromJSON(json: any): Charge {
    return ChargeFromJSONTyped(json, false);
}

export function ChargeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Charge {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'type': json['type'],
    };
}

export function ChargeToJSON(json: any): Charge {
    return ChargeToJSONTyped(json, false);
}

export function ChargeToJSONTyped(value?: Charge | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'type': value['type'],
    };
}

