/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CharacterAlignment
 */
export interface CharacterAlignment {
    /**
     * 
     * @type {number}
     * @memberof CharacterAlignment
     */
    end: number;
    /**
     * 
     * @type {number}
     * @memberof CharacterAlignment
     */
    start: number;
    /**
     * 
     * @type {string}
     * @memberof CharacterAlignment
     */
    text: string;
}

/**
 * Check if a given object implements the CharacterAlignment interface.
 */
export function instanceOfCharacterAlignment(value: object): value is CharacterAlignment {
    if (!('end' in value) || value['end'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function CharacterAlignmentFromJSON(json: any): CharacterAlignment {
    return CharacterAlignmentFromJSONTyped(json, false);
}

export function CharacterAlignmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CharacterAlignment {
    if (json == null) {
        return json;
    }
    return {
        
        'end': json['end'],
        'start': json['start'],
        'text': json['text'],
    };
}

export function CharacterAlignmentToJSON(json: any): CharacterAlignment {
    return CharacterAlignmentToJSONTyped(json, false);
}

export function CharacterAlignmentToJSONTyped(value?: CharacterAlignment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'end': value['end'],
        'start': value['start'],
        'text': value['text'],
    };
}

