/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Scene } from './Scene';
import {
    SceneFromJSON,
    SceneFromJSONTyped,
    SceneToJSON,
    SceneToJSONTyped,
} from './Scene';

/**
 * 
 * @export
 * @interface Episode
 */
export interface Episode {
    /**
     * 
     * @type {string}
     * @memberof Episode
     */
    id: string;
    /**
     * 
     * @type {Array<Scene>}
     * @memberof Episode
     */
    scenes: Array<Scene>;
}

/**
 * Check if a given object implements the Episode interface.
 */
export function instanceOfEpisode(value: object): value is Episode {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('scenes' in value) || value['scenes'] === undefined) return false;
    return true;
}

export function EpisodeFromJSON(json: any): Episode {
    return EpisodeFromJSONTyped(json, false);
}

export function EpisodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Episode {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'scenes': ((json['scenes'] as Array<any>).map(SceneFromJSON)),
    };
}

export function EpisodeToJSON(json: any): Episode {
    return EpisodeToJSONTyped(json, false);
}

export function EpisodeToJSONTyped(value?: Episode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'scenes': ((value['scenes'] as Array<any>).map(SceneToJSON)),
    };
}

