/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Faq
 */
export interface Faq {
    /**
     * 
     * @type {string}
     * @memberof Faq
     */
    answer: string;
    /**
     * 
     * @type {string}
     * @memberof Faq
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Faq
     */
    question: string;
}

/**
 * Check if a given object implements the Faq interface.
 */
export function instanceOfFaq(value: object): value is Faq {
    if (!('answer' in value) || value['answer'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('question' in value) || value['question'] === undefined) return false;
    return true;
}

export function FaqFromJSON(json: any): Faq {
    return FaqFromJSONTyped(json, false);
}

export function FaqFromJSONTyped(json: any, ignoreDiscriminator: boolean): Faq {
    if (json == null) {
        return json;
    }
    return {
        
        'answer': json['answer'],
        'id': json['id'],
        'question': json['question'],
    };
}

export function FaqToJSON(json: any): Faq {
    return FaqToJSONTyped(json, false);
}

export function FaqToJSONTyped(value?: Faq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'answer': value['answer'],
        'id': value['id'],
        'question': value['question'],
    };
}

