/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Flux2Pro
 */
export interface Flux2Pro {
    /**
     * 
     * @type {string}
     * @memberof Flux2Pro
     */
    falRequestId: string;
    /**
     * base64 return
     * @type {string}
     * @memberof Flux2Pro
     */
    file: string;
    /**
     * 
     * @type {string}
     * @memberof Flux2Pro
     */
    prompt: string;
    /**
     * 
     * @type {Flux2ProTypeEnum}
     * @memberof Flux2Pro
     */
    type: 'Flux2Pro';
}




/**
 * Check if a given object implements the Flux2Pro interface.
 */
export function instanceOfFlux2Pro(value: object): value is Flux2Pro {
    if (!('falRequestId' in value) || value['falRequestId'] === undefined) return false;
    if (!('file' in value) || value['file'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function Flux2ProFromJSON(json: any): Flux2Pro {
    return Flux2ProFromJSONTyped(json, false);
}

export function Flux2ProFromJSONTyped(json: any, ignoreDiscriminator: boolean): Flux2Pro {
    if (json == null) {
        return json;
    }
    return {
        
        'falRequestId': json['fal_request_id'],
        'file': json['file'],
        'prompt': json['prompt'],
        'type': json['type'],
    };
}

export function Flux2ProToJSON(json: any): Flux2Pro {
    return Flux2ProToJSONTyped(json, false);
}

export function Flux2ProToJSONTyped(value?: Flux2Pro | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fal_request_id': value['falRequestId'],
        'file': value['file'],
        'prompt': value['prompt'],
        'type': value['type'],
    };
}

