/* tslint:disable */
/* eslint-disable */
/**
 * femi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Flux2KleinI2I
 */
export interface Flux2KleinI2I {
    /**
     * 
     * @type {string}
     * @memberof Flux2KleinI2I
     */
    comfyRequestId: string;
    /**
     * base64 return
     * @type {string}
     * @memberof Flux2KleinI2I
     */
    file: string;
    /**
     * input subject image as base64 — data URI (web) or raw base64 (android/ios); type detected server-side
     * @type {string}
     * @memberof Flux2KleinI2I
     */
    image: string;
    /**
     * reference image as base64 — data URI (web) or raw base64 (android/ios); type detected server-side
     * @type {string}
     * @memberof Flux2KleinI2I
     */
    image2: string;
    /**
     * 
     * @type {string}
     * @memberof Flux2KleinI2I
     */
    prompt: string;
    /**
     * 
     * @type {Flux2KleinI2ITypeEnum}
     * @memberof Flux2KleinI2I
     */
    type: 'Flux2KleinI2I';
}




/**
 * Check if a given object implements the Flux2KleinI2I interface.
 */
export function instanceOfFlux2KleinI2I(value: object): value is Flux2KleinI2I {
    if (!('comfyRequestId' in value) || value['comfyRequestId'] === undefined) return false;
    if (!('file' in value) || value['file'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('image2' in value) || value['image2'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function Flux2KleinI2IFromJSON(json: any): Flux2KleinI2I {
    return Flux2KleinI2IFromJSONTyped(json, false);
}

export function Flux2KleinI2IFromJSONTyped(json: any, ignoreDiscriminator: boolean): Flux2KleinI2I {
    if (json == null) {
        return json;
    }
    return {
        
        'comfyRequestId': json['comfy_request_id'],
        'file': json['file'],
        'image': json['image'],
        'image2': json['image2'],
        'prompt': json['prompt'],
        'type': json['type'],
    };
}

export function Flux2KleinI2IToJSON(json: any): Flux2KleinI2I {
    return Flux2KleinI2IToJSONTyped(json, false);
}

export function Flux2KleinI2IToJSONTyped(value?: Flux2KleinI2I | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comfy_request_id': value['comfyRequestId'],
        'file': value['file'],
        'image': value['image'],
        'image2': value['image2'],
        'prompt': value['prompt'],
        'type': value['type'],
    };
}

