/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GooglePay
 */
export interface GooglePay {
    /**
     * 
     * @type {number}
     * @memberof GooglePay
     */
    credit: number;
    /**
     * 
     * @type {boolean}
     * @memberof GooglePay
     */
    loaded: boolean;
    /**
     * 
     * @type {string}
     * @memberof GooglePay
     */
    orderId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GooglePay
     */
    packageName: string;
    /**
     * 
     * @type {string}
     * @memberof GooglePay
     */
    productId: string;
    /**
     * 
     * @type {string}
     * @memberof GooglePay
     */
    purchaseToken: string;
    /**
     * 
     * @type {GooglePayTypeEnum}
     * @memberof GooglePay
     */
    type: GooglePayTypeEnum;
}

/**
* @export
* @enum {string}
*/
export enum GooglePayTypeEnum {
    GooglePay = 'GooglePay'
}


/**
 * Check if a given object implements the GooglePay interface.
 */
export function instanceOfGooglePay(value: object): value is GooglePay {
    if (!('credit' in value) || value['credit'] === undefined) return false;
    if (!('loaded' in value) || value['loaded'] === undefined) return false;
    if (!('packageName' in value) || value['packageName'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('purchaseToken' in value) || value['purchaseToken'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function GooglePayFromJSON(json: any): GooglePay {
    return GooglePayFromJSONTyped(json, false);
}

export function GooglePayFromJSONTyped(json: any, ignoreDiscriminator: boolean): GooglePay {
    if (json == null) {
        return json;
    }
    return {
        
        'credit': json['credit'],
        'loaded': json['loaded'],
        'orderId': json['order_id'] == null ? undefined : json['order_id'],
        'packageName': json['package_name'],
        'productId': json['product_id'],
        'purchaseToken': json['purchase_token'],
        'type': json['type'],
    };
}

export function GooglePayToJSON(json: any): GooglePay {
    return GooglePayToJSONTyped(json, false);
}

export function GooglePayToJSONTyped(value?: GooglePay | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'credit': value['credit'],
        'loaded': value['loaded'],
        'order_id': value['orderId'],
        'package_name': value['packageName'],
        'product_id': value['productId'],
        'purchase_token': value['purchaseToken'],
        'type': value['type'],
    };
}

