/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Ltx23A2V
 */
export interface Ltx23A2V {
    /**
     * input audio as base64 — data URI (web) or raw base64 (android/ios), empty if unused; type detected server-side
     * @type {string}
     * @memberof Ltx23A2V
     */
    audio: string;
    /**
     * 
     * @type {string}
     * @memberof Ltx23A2V
     */
    comfyRequestId: string;
    /**
     * base64 return
     * @type {string}
     * @memberof Ltx23A2V
     */
    file: string;
    /**
     * input image as base64 — data URI (web) or raw base64 (android/ios), empty if unused; type detected server-side
     * @type {string}
     * @memberof Ltx23A2V
     */
    image: string;
    /**
     * 
     * @type {string}
     * @memberof Ltx23A2V
     */
    prompt: string;
    /**
     * 
     * @type {Ltx23A2VTypeEnum}
     * @memberof Ltx23A2V
     */
    type: Ltx23A2VTypeEnum;
}

/**
* @export
* @enum {string}
*/
export enum Ltx23A2VTypeEnum {
    Ltx23A2V = 'Ltx2_3A2V'
}


/**
 * Check if a given object implements the Ltx23A2V interface.
 */
export function instanceOfLtx23A2V(value: object): value is Ltx23A2V {
    if (!('audio' in value) || value['audio'] === undefined) return false;
    if (!('comfyRequestId' in value) || value['comfyRequestId'] === undefined) return false;
    if (!('file' in value) || value['file'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function Ltx23A2VFromJSON(json: any): Ltx23A2V {
    return Ltx23A2VFromJSONTyped(json, false);
}

export function Ltx23A2VFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ltx23A2V {
    if (json == null) {
        return json;
    }
    return {
        
        'audio': json['audio'],
        'comfyRequestId': json['comfy_request_id'],
        'file': json['file'],
        'image': json['image'],
        'prompt': json['prompt'],
        'type': json['type'],
    };
}

export function Ltx23A2VToJSON(json: any): Ltx23A2V {
    return Ltx23A2VToJSONTyped(json, false);
}

export function Ltx23A2VToJSONTyped(value?: Ltx23A2V | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'audio': value['audio'],
        'comfy_request_id': value['comfyRequestId'],
        'file': value['file'],
        'image': value['image'],
        'prompt': value['prompt'],
        'type': value['type'],
    };
}

