/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CharacterAlignment } from './CharacterAlignment';
import {
    CharacterAlignmentFromJSON,
    CharacterAlignmentFromJSONTyped,
    CharacterAlignmentToJSON,
    CharacterAlignmentToJSONTyped,
} from './CharacterAlignment';
import type { WordAlignment } from './WordAlignment';
import {
    WordAlignmentFromJSON,
    WordAlignmentFromJSONTyped,
    WordAlignmentToJSON,
    WordAlignmentToJSONTyped,
} from './WordAlignment';

/**
 * 
 * @export
 * @interface LyricSync
 */
export interface LyricSync {
    /**
     * 
     * @type {string}
     * @memberof LyricSync
     */
    audio: string;
    /**
     * 
     * @type {Array<CharacterAlignment>}
     * @memberof LyricSync
     */
    characters?: Array<CharacterAlignment>;
    /**
     * 
     * @type {number}
     * @memberof LyricSync
     */
    credit?: number;
    /**
     * 
     * @type {string}
     * @memberof LyricSync
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof LyricSync
     */
    loss?: number;
    /**
     * 
     * @type {string}
     * @memberof LyricSync
     */
    lyrics: string;
    /**
     * 
     * @type {string}
     * @memberof LyricSync
     */
    userId?: string;
    /**
     * 
     * @type {Array<WordAlignment>}
     * @memberof LyricSync
     */
    words?: Array<WordAlignment>;
}

/**
 * Check if a given object implements the LyricSync interface.
 */
export function instanceOfLyricSync(value: object): value is LyricSync {
    if (!('audio' in value) || value['audio'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('lyrics' in value) || value['lyrics'] === undefined) return false;
    return true;
}

export function LyricSyncFromJSON(json: any): LyricSync {
    return LyricSyncFromJSONTyped(json, false);
}

export function LyricSyncFromJSONTyped(json: any, ignoreDiscriminator: boolean): LyricSync {
    if (json == null) {
        return json;
    }
    return {
        
        'audio': json['audio'],
        'characters': json['characters'] == null ? undefined : ((json['characters'] as Array<any>).map(CharacterAlignmentFromJSON)),
        'credit': json['credit'] == null ? undefined : json['credit'],
        'id': json['id'],
        'loss': json['loss'] == null ? undefined : json['loss'],
        'lyrics': json['lyrics'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'words': json['words'] == null ? undefined : ((json['words'] as Array<any>).map(WordAlignmentFromJSON)),
    };
}

export function LyricSyncToJSON(json: any): LyricSync {
    return LyricSyncToJSONTyped(json, false);
}

export function LyricSyncToJSONTyped(value?: LyricSync | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'audio': value['audio'],
        'characters': value['characters'] == null ? undefined : ((value['characters'] as Array<any>).map(CharacterAlignmentToJSON)),
        'credit': value['credit'],
        'id': value['id'],
        'loss': value['loss'],
        'lyrics': value['lyrics'],
        'user_id': value['userId'],
        'words': value['words'] == null ? undefined : ((value['words'] as Array<any>).map(WordAlignmentToJSON)),
    };
}

