/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CharacterAlignment } from './CharacterAlignment';
import {
    CharacterAlignmentFromJSON,
    CharacterAlignmentFromJSONTyped,
    CharacterAlignmentToJSON,
    CharacterAlignmentToJSONTyped,
} from './CharacterAlignment';
import type { WordAlignment } from './WordAlignment';
import {
    WordAlignmentFromJSON,
    WordAlignmentFromJSONTyped,
    WordAlignmentToJSON,
    WordAlignmentToJSONTyped,
} from './WordAlignment';

/**
 * 
 * @export
 * @interface LyricSync
 */
export interface LyricSync {
    /**
     * input image as base64 — data URI (web) or raw base64 (android/ios), empty if unused; type detected server-side
     * @type {string}
     * @memberof LyricSync
     */
    audio: string;
    /**
     * return
     * @type {Array<CharacterAlignment>}
     * @memberof LyricSync
     */
    characters: Array<CharacterAlignment>;
    /**
     * 
     * @type {string}
     * @memberof LyricSync
     */
    lyrics: string;
    /**
     * 
     * @type {LyricSyncTypeEnum}
     * @memberof LyricSync
     */
    type: LyricSyncTypeEnum;
    /**
     * return
     * @type {Array<WordAlignment>}
     * @memberof LyricSync
     */
    words: Array<WordAlignment>;
}

/**
* @export
* @enum {string}
*/
export enum LyricSyncTypeEnum {
    LyricSync = 'LyricSync'
}


/**
 * Check if a given object implements the LyricSync interface.
 */
export function instanceOfLyricSync(value: object): value is LyricSync {
    if (!('audio' in value) || value['audio'] === undefined) return false;
    if (!('characters' in value) || value['characters'] === undefined) return false;
    if (!('lyrics' in value) || value['lyrics'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('words' in value) || value['words'] === undefined) return false;
    return true;
}

export function LyricSyncFromJSON(json: any): LyricSync {
    return LyricSyncFromJSONTyped(json, false);
}

export function LyricSyncFromJSONTyped(json: any, ignoreDiscriminator: boolean): LyricSync {
    if (json == null) {
        return json;
    }
    return {
        
        'audio': json['audio'],
        'characters': ((json['characters'] as Array<any>).map(CharacterAlignmentFromJSON)),
        'lyrics': json['lyrics'],
        'type': json['type'],
        'words': ((json['words'] as Array<any>).map(WordAlignmentFromJSON)),
    };
}

export function LyricSyncToJSON(json: any): LyricSync {
    return LyricSyncToJSONTyped(json, false);
}

export function LyricSyncToJSONTyped(value?: LyricSync | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'audio': value['audio'],
        'characters': ((value['characters'] as Array<any>).map(CharacterAlignmentToJSON)),
        'lyrics': value['lyrics'],
        'type': value['type'],
        'words': ((value['words'] as Array<any>).map(WordAlignmentToJSON)),
    };
}

