/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Status } from './Status';
import {
    StatusFromJSON,
    StatusFromJSONTyped,
    StatusToJSON,
    StatusToJSONTyped,
} from './Status';

/**
 * 
 * @export
 * @interface Model
 */
export interface Model {
    /**
     * 
     * @type {number}
     * @memberof Model
     */
    amountCents: number;
    /**
     * 
     * @type {number}
     * @memberof Model
     */
    credit?: number;
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof Model
     */
    loaded?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    paymentUrl?: string | null;
    /**
     * 
     * @type {Status}
     * @memberof Model
     */
    status: Status;
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    stripePaymentIntentId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    stripeSessionId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    userId: string;
}



/**
 * Check if a given object implements the Model interface.
 */
export function instanceOfModel(value: object): value is Model {
    if (!('amountCents' in value) || value['amountCents'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function ModelFromJSON(json: any): Model {
    return ModelFromJSONTyped(json, false);
}

export function ModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model {
    if (json == null) {
        return json;
    }
    return {
        
        'amountCents': json['amount_cents'],
        'credit': json['credit'] == null ? undefined : json['credit'],
        'id': json['id'],
        'loaded': json['loaded'] == null ? undefined : json['loaded'],
        'paymentUrl': json['payment_url'] == null ? undefined : json['payment_url'],
        'status': StatusFromJSON(json['status']),
        'stripePaymentIntentId': json['stripe_payment_intent_id'] == null ? undefined : json['stripe_payment_intent_id'],
        'stripeSessionId': json['stripe_session_id'] == null ? undefined : json['stripe_session_id'],
        'userId': json['user_id'],
    };
}

export function ModelToJSON(json: any): Model {
    return ModelToJSONTyped(json, false);
}

export function ModelToJSONTyped(value?: Model | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount_cents': value['amountCents'],
        'credit': value['credit'],
        'id': value['id'],
        'loaded': value['loaded'],
        'payment_url': value['paymentUrl'],
        'status': StatusToJSON(value['status']),
        'stripe_payment_intent_id': value['stripePaymentIntentId'],
        'stripe_session_id': value['stripeSessionId'],
        'user_id': value['userId'],
    };
}

