/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NanoBanana2
 */
export interface NanoBanana2 {
    /**
     * 
     * @type {string}
     * @memberof NanoBanana2
     */
    falRequestId: string;
    /**
     * base64 return
     * @type {string}
     * @memberof NanoBanana2
     */
    file: string;
    /**
     * 
     * @type {string}
     * @memberof NanoBanana2
     */
    prompt: string;
    /**
     * 
     * @type {NanoBanana2TypeEnum}
     * @memberof NanoBanana2
     */
    type: 'NanoBanana2';
}




/**
 * Check if a given object implements the NanoBanana2 interface.
 */
export function instanceOfNanoBanana2(value: object): value is NanoBanana2 {
    if (!('falRequestId' in value) || value['falRequestId'] === undefined) return false;
    if (!('file' in value) || value['file'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function NanoBanana2FromJSON(json: any): NanoBanana2 {
    return NanoBanana2FromJSONTyped(json, false);
}

export function NanoBanana2FromJSONTyped(json: any, ignoreDiscriminator: boolean): NanoBanana2 {
    if (json == null) {
        return json;
    }
    return {
        
        'falRequestId': json['fal_request_id'],
        'file': json['file'],
        'prompt': json['prompt'],
        'type': json['type'],
    };
}

export function NanoBanana2ToJSON(json: any): NanoBanana2 {
    return NanoBanana2ToJSONTyped(json, false);
}

export function NanoBanana2ToJSONTyped(value?: NanoBanana2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fal_request_id': value['falRequestId'],
        'file': value['file'],
        'prompt': value['prompt'],
        'type': value['type'],
    };
}

