/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PayStatus } from './PayStatus';
import {
    PayStatusFromJSON,
    PayStatusFromJSONTyped,
    PayStatusToJSON,
    PayStatusToJSONTyped,
} from './PayStatus';
import type { PayProvider } from './PayProvider';
import {
    PayProviderFromJSON,
    PayProviderFromJSONTyped,
    PayProviderToJSON,
    PayProviderToJSONTyped,
} from './PayProvider';

/**
 * 
 * @export
 * @interface Pay
 */
export interface Pay {
    /**
     * 
     * @type {number}
     * @memberof Pay
     */
    credit?: number;
    /**
     * 
     * @type {string}
     * @memberof Pay
     */
    currency?: string;
    /**
     * uuid v7
     * @type {string}
     * @memberof Pay
     */
    id: string;
    /**
     * Signed transaction JWS from StoreKit; the input to Apple verification.
     * @type {string}
     * @memberof Pay
     */
    jws?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Pay
     */
    loaded?: boolean;
    /**
     * Google's per-purchase `orderId`, returned by the Play Developer API (not
     * the client). Not used for dedup — `ref_id` is — because promo-code
     * purchases may have no `orderId`.
     * @type {string}
     * @memberof Pay
     */
    orderId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Pay
     */
    packageName?: string;
    /**
     * 
     * @type {number}
     * @memberof Pay
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof Pay
     */
    productId?: string;
    /**
     * Selects the verification path: Apple App Store vs Google Play.
     * @type {PayProvider}
     * @memberof Pay
     */
    provider: PayProvider;
    /**
     * Globally-unique purchase id, used as the idempotency key for both stores.
     * Apple: the `transactionId`, extracted server-side from the verified JWS
     *   (empty on the incoming request — the server fills it in).
     * Google: the `purchaseToken`, sent by the client. It is both the input to
     *   Play Developer API verification and the idempotency key.
     * @type {string}
     * @memberof Pay
     */
    refId?: string;
    /**
     * 
     * @type {PayStatus}
     * @memberof Pay
     */
    status?: PayStatus;
    /**
     * 
     * @type {string}
     * @memberof Pay
     */
    userId: string;
}



/**
 * Check if a given object implements the Pay interface.
 */
export function instanceOfPay(value: object): value is Pay {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function PayFromJSON(json: any): Pay {
    return PayFromJSONTyped(json, false);
}

export function PayFromJSONTyped(json: any, ignoreDiscriminator: boolean): Pay {
    if (json == null) {
        return json;
    }
    return {
        
        'credit': json['credit'] == null ? undefined : json['credit'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'id': json['id'],
        'jws': json['jws'] == null ? undefined : json['jws'],
        'loaded': json['loaded'] == null ? undefined : json['loaded'],
        'orderId': json['order_id'] == null ? undefined : json['order_id'],
        'packageName': json['package_name'] == null ? undefined : json['package_name'],
        'price': json['price'] == null ? undefined : json['price'],
        'productId': json['product_id'] == null ? undefined : json['product_id'],
        'provider': PayProviderFromJSON(json['provider']),
        'refId': json['ref_id'] == null ? undefined : json['ref_id'],
        'status': json['status'] == null ? undefined : PayStatusFromJSON(json['status']),
        'userId': json['user_id'],
    };
}

export function PayToJSON(json: any): Pay {
    return PayToJSONTyped(json, false);
}

export function PayToJSONTyped(value?: Pay | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'credit': value['credit'],
        'currency': value['currency'],
        'id': value['id'],
        'jws': value['jws'],
        'loaded': value['loaded'],
        'order_id': value['orderId'],
        'package_name': value['packageName'],
        'price': value['price'],
        'product_id': value['productId'],
        'provider': PayProviderToJSON(value['provider']),
        'ref_id': value['refId'],
        'status': PayStatusToJSON(value['status']),
        'user_id': value['userId'],
    };
}

