/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum PayStatus {
    Pending = 'Pending',
    Completed = 'Completed',
    Failed = 'Failed'
}


export function instanceOfPayStatus(value: any): boolean {
    for (const key in PayStatus) {
        if (Object.prototype.hasOwnProperty.call(PayStatus, key)) {
            if (PayStatus[key as keyof typeof PayStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PayStatusFromJSON(json: any): PayStatus {
    return PayStatusFromJSONTyped(json, false);
}

export function PayStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayStatus {
    return json as PayStatus;
}

export function PayStatusToJSON(value?: PayStatus | null): any {
    return value as any;
}

export function PayStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): PayStatus {
    return value as PayStatus;
}

