/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Faq } from './Faq';
import {
    FaqFromJSON,
    FaqFromJSONTyped,
    FaqToJSON,
    FaqToJSONTyped,
} from './Faq';
import type { AudioLine } from './AudioLine';
import {
    AudioLineFromJSON,
    AudioLineFromJSONTyped,
    AudioLineToJSON,
    AudioLineToJSONTyped,
} from './AudioLine';
import type { Season } from './Season';
import {
    SeasonFromJSON,
    SeasonFromJSONTyped,
    SeasonToJSON,
    SeasonToJSONTyped,
} from './Season';

/**
 * 
 * @export
 * @interface Project
 */
export interface Project {
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    about: string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    audio: string;
    /**
     * 
     * @type {Array<AudioLine>}
     * @memberof Project
     */
    audioLines: Array<AudioLine>;
    /**
     * 
     * @type {Array<Faq>}
     * @memberof Project
     */
    faqs: Array<Faq>;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    genre: string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    playlist: string;
    /**
     * 
     * @type {Array<Season>}
     * @memberof Project
     */
    seasons: Array<Season>;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    summary: string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    userId: string;
}

/**
 * Check if a given object implements the Project interface.
 */
export function instanceOfProject(value: object): value is Project {
    if (!('about' in value) || value['about'] === undefined) return false;
    if (!('audio' in value) || value['audio'] === undefined) return false;
    if (!('audioLines' in value) || value['audioLines'] === undefined) return false;
    if (!('faqs' in value) || value['faqs'] === undefined) return false;
    if (!('genre' in value) || value['genre'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('playlist' in value) || value['playlist'] === undefined) return false;
    if (!('seasons' in value) || value['seasons'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function ProjectFromJSON(json: any): Project {
    return ProjectFromJSONTyped(json, false);
}

export function ProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): Project {
    if (json == null) {
        return json;
    }
    return {
        
        'about': json['about'],
        'audio': json['audio'],
        'audioLines': ((json['audio_lines'] as Array<any>).map(AudioLineFromJSON)),
        'faqs': ((json['faqs'] as Array<any>).map(FaqFromJSON)),
        'genre': json['genre'],
        'id': json['id'],
        'playlist': json['playlist'],
        'seasons': ((json['seasons'] as Array<any>).map(SeasonFromJSON)),
        'summary': json['summary'],
        'userId': json['user_id'],
    };
}

export function ProjectToJSON(json: any): Project {
    return ProjectToJSONTyped(json, false);
}

export function ProjectToJSONTyped(value?: Project | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'about': value['about'],
        'audio': value['audio'],
        'audio_lines': ((value['audioLines'] as Array<any>).map(AudioLineToJSON)),
        'faqs': ((value['faqs'] as Array<any>).map(FaqToJSON)),
        'genre': value['genre'],
        'id': value['id'],
        'playlist': value['playlist'],
        'seasons': ((value['seasons'] as Array<any>).map(SeasonToJSON)),
        'summary': value['summary'],
        'user_id': value['userId'],
    };
}

