/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Status } from './Status';
import {
    StatusFromJSON,
    StatusFromJSONTyped,
    StatusToJSON,
    StatusToJSONTyped,
} from './Status';

/**
 * 
 * @export
 * @interface Revolut
 */
export interface Revolut {
    /**
     * 
     * @type {number}
     * @memberof Revolut
     */
    amountCents: number;
    /**
     * 
     * @type {number}
     * @memberof Revolut
     */
    credit?: number;
    /**
     * 
     * @type {string}
     * @memberof Revolut
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof Revolut
     */
    loaded?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Revolut
     */
    paymentUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Revolut
     */
    revolutOrderId?: string | null;
    /**
     * 
     * @type {Status}
     * @memberof Revolut
     */
    status: Status;
    /**
     * 
     * @type {string}
     * @memberof Revolut
     */
    userId: string;
}



/**
 * Check if a given object implements the Revolut interface.
 */
export function instanceOfRevolut(value: object): value is Revolut {
    if (!('amountCents' in value) || value['amountCents'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function RevolutFromJSON(json: any): Revolut {
    return RevolutFromJSONTyped(json, false);
}

export function RevolutFromJSONTyped(json: any, ignoreDiscriminator: boolean): Revolut {
    if (json == null) {
        return json;
    }
    return {
        
        'amountCents': json['amount_cents'],
        'credit': json['credit'] == null ? undefined : json['credit'],
        'id': json['id'],
        'loaded': json['loaded'] == null ? undefined : json['loaded'],
        'paymentUrl': json['payment_url'] == null ? undefined : json['payment_url'],
        'revolutOrderId': json['revolut_order_id'] == null ? undefined : json['revolut_order_id'],
        'status': StatusFromJSON(json['status']),
        'userId': json['user_id'],
    };
}

export function RevolutToJSON(json: any): Revolut {
    return RevolutToJSONTyped(json, false);
}

export function RevolutToJSONTyped(value?: Revolut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount_cents': value['amountCents'],
        'credit': value['credit'],
        'id': value['id'],
        'loaded': value['loaded'],
        'payment_url': value['paymentUrl'],
        'revolut_order_id': value['revolutOrderId'],
        'status': StatusToJSON(value['status']),
        'user_id': value['userId'],
    };
}

