/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Shot } from './Shot';
import {
    ShotFromJSON,
    ShotFromJSONTyped,
    ShotToJSON,
    ShotToJSONTyped,
} from './Shot';

/**
 * 
 * @export
 * @interface Scene
 */
export interface Scene {
    /**
     * 
     * @type {string}
     * @memberof Scene
     */
    audioLineId: string;
    /**
     * 
     * @type {string}
     * @memberof Scene
     */
    id: string;
    /**
     * 
     * @type {Array<Shot>}
     * @memberof Scene
     */
    shots: Array<Shot>;
    /**
     * 
     * @type {string}
     * @memberof Scene
     */
    text: string;
}

/**
 * Check if a given object implements the Scene interface.
 */
export function instanceOfScene(value: object): value is Scene {
    if (!('audioLineId' in value) || value['audioLineId'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('shots' in value) || value['shots'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function SceneFromJSON(json: any): Scene {
    return SceneFromJSONTyped(json, false);
}

export function SceneFromJSONTyped(json: any, ignoreDiscriminator: boolean): Scene {
    if (json == null) {
        return json;
    }
    return {
        
        'audioLineId': json['audio_line_id'],
        'id': json['id'],
        'shots': ((json['shots'] as Array<any>).map(ShotFromJSON)),
        'text': json['text'],
    };
}

export function SceneToJSON(json: any): Scene {
    return SceneToJSONTyped(json, false);
}

export function SceneToJSONTyped(value?: Scene | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'audio_line_id': value['audioLineId'],
        'id': value['id'],
        'shots': ((value['shots'] as Array<any>).map(ShotToJSON)),
        'text': value['text'],
    };
}

