/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Episode } from './Episode';
import {
    EpisodeFromJSON,
    EpisodeFromJSONTyped,
    EpisodeToJSON,
    EpisodeToJSONTyped,
} from './Episode';

/**
 * 
 * @export
 * @interface Season
 */
export interface Season {
    /**
     * 
     * @type {Array<Episode>}
     * @memberof Season
     */
    episodes: Array<Episode>;
    /**
     * 
     * @type {string}
     * @memberof Season
     */
    id: string;
}

/**
 * Check if a given object implements the Season interface.
 */
export function instanceOfSeason(value: object): value is Season {
    if (!('episodes' in value) || value['episodes'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function SeasonFromJSON(json: any): Season {
    return SeasonFromJSONTyped(json, false);
}

export function SeasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): Season {
    if (json == null) {
        return json;
    }
    return {
        
        'episodes': ((json['episodes'] as Array<any>).map(EpisodeFromJSON)),
        'id': json['id'],
    };
}

export function SeasonToJSON(json: any): Season {
    return SeasonToJSONTyped(json, false);
}

export function SeasonToJSONTyped(value?: Season | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'episodes': ((value['episodes'] as Array<any>).map(EpisodeToJSON)),
        'id': value['id'],
    };
}

