/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Status } from './Status';
import {
    StatusFromJSON,
    StatusFromJSONTyped,
    StatusToJSON,
    StatusToJSONTyped,
} from './Status';

/**
 * 
 * @export
 * @interface Solana
 */
export interface Solana {
    /**
     * 
     * @type {number}
     * @memberof Solana
     */
    amountCents: number;
    /**
     * 
     * @type {number}
     * @memberof Solana
     */
    credit?: number;
    /**
     * 
     * @type {string}
     * @memberof Solana
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof Solana
     */
    loaded?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Solana
     */
    pubkey: string;
    /**
     * 
     * @type {number}
     * @memberof Solana
     */
    quotedOutUnits?: number;
    /**
     * 
     * @type {string}
     * @memberof Solana
     */
    requestId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Solana
     */
    signature?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Solana
     */
    signedTx?: string | null;
    /**
     * 
     * @type {Status}
     * @memberof Solana
     */
    status: Status;
    /**
     * 
     * @type {string}
     * @memberof Solana
     */
    unsignedTx?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Solana
     */
    userId: string;
}



/**
 * Check if a given object implements the Solana interface.
 */
export function instanceOfSolana(value: object): value is Solana {
    if (!('amountCents' in value) || value['amountCents'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('pubkey' in value) || value['pubkey'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function SolanaFromJSON(json: any): Solana {
    return SolanaFromJSONTyped(json, false);
}

export function SolanaFromJSONTyped(json: any, ignoreDiscriminator: boolean): Solana {
    if (json == null) {
        return json;
    }
    return {
        
        'amountCents': json['amount_cents'],
        'credit': json['credit'] == null ? undefined : json['credit'],
        'id': json['id'],
        'loaded': json['loaded'] == null ? undefined : json['loaded'],
        'pubkey': json['pubkey'],
        'quotedOutUnits': json['quoted_out_units'] == null ? undefined : json['quoted_out_units'],
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
        'signature': json['signature'] == null ? undefined : json['signature'],
        'signedTx': json['signed_tx'] == null ? undefined : json['signed_tx'],
        'status': StatusFromJSON(json['status']),
        'unsignedTx': json['unsigned_tx'] == null ? undefined : json['unsigned_tx'],
        'userId': json['user_id'],
    };
}

export function SolanaToJSON(json: any): Solana {
    return SolanaToJSONTyped(json, false);
}

export function SolanaToJSONTyped(value?: Solana | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount_cents': value['amountCents'],
        'credit': value['credit'],
        'id': value['id'],
        'loaded': value['loaded'],
        'pubkey': value['pubkey'],
        'quoted_out_units': value['quotedOutUnits'],
        'request_id': value['requestId'],
        'signature': value['signature'],
        'signed_tx': value['signedTx'],
        'status': StatusToJSON(value['status']),
        'unsigned_tx': value['unsignedTx'],
        'user_id': value['userId'],
    };
}

