/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Stripe
 */
export interface Stripe {
    /**
     * 
     * @type {number}
     * @memberof Stripe
     */
    amountCents: number;
    /**
     * 
     * @type {number}
     * @memberof Stripe
     */
    credit: number;
    /**
     * 
     * @type {boolean}
     * @memberof Stripe
     */
    loaded: boolean;
    /**
     * 
     * @type {string}
     * @memberof Stripe
     */
    paymentUrl: string;
    /**
     * 
     * @type {string}
     * @memberof Stripe
     */
    stripePaymentIntentId: string;
    /**
     * 
     * @type {string}
     * @memberof Stripe
     */
    stripeSessionId: string;
    /**
     * 
     * @type {StripeTypeEnum}
     * @memberof Stripe
     */
    type: 'Stripe';
}




/**
 * Check if a given object implements the Stripe interface.
 */
export function instanceOfStripe(value: object): value is Stripe {
    if (!('amountCents' in value) || value['amountCents'] === undefined) return false;
    if (!('credit' in value) || value['credit'] === undefined) return false;
    if (!('loaded' in value) || value['loaded'] === undefined) return false;
    if (!('paymentUrl' in value) || value['paymentUrl'] === undefined) return false;
    if (!('stripePaymentIntentId' in value) || value['stripePaymentIntentId'] === undefined) return false;
    if (!('stripeSessionId' in value) || value['stripeSessionId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function StripeFromJSON(json: any): Stripe {
    return StripeFromJSONTyped(json, false);
}

export function StripeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Stripe {
    if (json == null) {
        return json;
    }
    return {
        
        'amountCents': json['amount_cents'],
        'credit': json['credit'],
        'loaded': json['loaded'],
        'paymentUrl': json['payment_url'],
        'stripePaymentIntentId': json['stripe_payment_intent_id'],
        'stripeSessionId': json['stripe_session_id'],
        'type': json['type'],
    };
}

export function StripeToJSON(json: any): Stripe {
    return StripeToJSONTyped(json, false);
}

export function StripeToJSONTyped(value?: Stripe | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount_cents': value['amountCents'],
        'credit': value['credit'],
        'loaded': value['loaded'],
        'payment_url': value['paymentUrl'],
        'stripe_payment_intent_id': value['stripePaymentIntentId'],
        'stripe_session_id': value['stripeSessionId'],
        'type': value['type'],
    };
}

