/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * default values
 * @export
 * @interface Upload
 */
export interface Upload {
    /**
     * 
     * @type {number}
     * @memberof Upload
     */
    credit: number;
    /**
     * 
     * @type {string}
     * @memberof Upload
     */
    file: string;
    /**
     * uuid v7
     * @type {string}
     * @memberof Upload
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Upload
     */
    userId: string;
}

/**
 * Check if a given object implements the Upload interface.
 */
export function instanceOfUpload(value: object): value is Upload {
    if (!('credit' in value) || value['credit'] === undefined) return false;
    if (!('file' in value) || value['file'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function UploadFromJSON(json: any): Upload {
    return UploadFromJSONTyped(json, false);
}

export function UploadFromJSONTyped(json: any, ignoreDiscriminator: boolean): Upload {
    if (json == null) {
        return json;
    }
    return {
        
        'credit': json['credit'],
        'file': json['file'],
        'id': json['id'],
        'userId': json['user_id'],
    };
}

export function UploadToJSON(json: any): Upload {
    return UploadToJSONTyped(json, false);
}

export function UploadToJSONTyped(value?: Upload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'credit': value['credit'],
        'file': value['file'],
        'id': value['id'],
        'user_id': value['userId'],
    };
}

