/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Status } from './Status';
import {
    StatusFromJSON,
    StatusFromJSONTyped,
    StatusToJSON,
    StatusToJSONTyped,
} from './Status';

/**
 * 
 * @export
 * @interface Wise
 */
export interface Wise {
    /**
     * 
     * @type {number}
     * @memberof Wise
     */
    amountCents: number;
    /**
     * 
     * @type {number}
     * @memberof Wise
     */
    credit?: number;
    /**
     * 
     * @type {string}
     * @memberof Wise
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof Wise
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof Wise
     */
    loaded?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Wise
     */
    reference: string;
    /**
     * 
     * @type {Status}
     * @memberof Wise
     */
    status: Status;
    /**
     * 
     * @type {string}
     * @memberof Wise
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof Wise
     */
    wiseCreditId?: string | null;
}



/**
 * Check if a given object implements the Wise interface.
 */
export function instanceOfWise(value: object): value is Wise {
    if (!('amountCents' in value) || value['amountCents'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('reference' in value) || value['reference'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function WiseFromJSON(json: any): Wise {
    return WiseFromJSONTyped(json, false);
}

export function WiseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Wise {
    if (json == null) {
        return json;
    }
    return {
        
        'amountCents': json['amount_cents'],
        'credit': json['credit'] == null ? undefined : json['credit'],
        'currency': json['currency'],
        'id': json['id'],
        'loaded': json['loaded'] == null ? undefined : json['loaded'],
        'reference': json['reference'],
        'status': StatusFromJSON(json['status']),
        'userId': json['user_id'],
        'wiseCreditId': json['wise_credit_id'] == null ? undefined : json['wise_credit_id'],
    };
}

export function WiseToJSON(json: any): Wise {
    return WiseToJSONTyped(json, false);
}

export function WiseToJSONTyped(value?: Wise | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount_cents': value['amountCents'],
        'credit': value['credit'],
        'currency': value['currency'],
        'id': value['id'],
        'loaded': value['loaded'],
        'reference': value['reference'],
        'status': StatusToJSON(value['status']),
        'user_id': value['userId'],
        'wise_credit_id': value['wiseCreditId'],
    };
}

