/* tslint:disable */
/* eslint-disable */
/**
 * femi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WordAlignment
 */
export interface WordAlignment {
    /**
     * 
     * @type {number}
     * @memberof WordAlignment
     */
    end: number;
    /**
     * 
     * @type {number}
     * @memberof WordAlignment
     */
    loss: number;
    /**
     * 
     * @type {number}
     * @memberof WordAlignment
     */
    start: number;
    /**
     * 
     * @type {string}
     * @memberof WordAlignment
     */
    text: string;
}


/**
 * Check if a given object implements the WordAlignment interface.
 */
export function instanceOfWordAlignment(value: object): value is WordAlignment {
    if (!('end' in value) || value['end'] === undefined) return false;
    if (!('loss' in value) || value['loss'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function WordAlignmentFromJSON(json: any): WordAlignment {
    return WordAlignmentFromJSONTyped(json, false);
}

export function WordAlignmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): WordAlignment {
    if (json == null) {
        return json;
    }
    return {
        
        'end': json['end'],
        'loss': json['loss'],
        'start': json['start'],
        'text': json['text'],
    };
}

export function WordAlignmentToJSON(json: any): WordAlignment {
    return WordAlignmentToJSONTyped(json, false);
}

export function WordAlignmentToJSONTyped(value?: WordAlignment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'end': value['end'],
        'loss': value['loss'],
        'start': value['start'],
        'text': value['text'],
    };
}

