/* tslint:disable */
/* eslint-disable */
/**
 * femi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ZImageTurbo
 */
export interface ZImageTurbo {
    /**
     * 
     * @type {string}
     * @memberof ZImageTurbo
     */
    falRequestId: string;
    /**
     * base64 return
     * @type {string}
     * @memberof ZImageTurbo
     */
    file: string;
    /**
     * 
     * @type {string}
     * @memberof ZImageTurbo
     */
    prompt: string;
    /**
     * 
     * @type {ZImageTurboTypeEnum}
     * @memberof ZImageTurbo
     */
    type: 'ZImageTurbo';
}




/**
 * Check if a given object implements the ZImageTurbo interface.
 */
export function instanceOfZImageTurbo(value: object): value is ZImageTurbo {
    if (!('falRequestId' in value) || value['falRequestId'] === undefined) return false;
    if (!('file' in value) || value['file'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ZImageTurboFromJSON(json: any): ZImageTurbo {
    return ZImageTurboFromJSONTyped(json, false);
}

export function ZImageTurboFromJSONTyped(json: any, ignoreDiscriminator: boolean): ZImageTurbo {
    if (json == null) {
        return json;
    }
    return {
        
        'falRequestId': json['fal_request_id'],
        'file': json['file'],
        'prompt': json['prompt'],
        'type': json['type'],
    };
}

export function ZImageTurboToJSON(json: any): ZImageTurbo {
    return ZImageTurboToJSONTyped(json, false);
}

export function ZImageTurboToJSONTyped(value?: ZImageTurbo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fal_request_id': value['falRequestId'],
        'file': value['file'],
        'prompt': value['prompt'],
        'type': value['type'],
    };
}

